"use client";
import React from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { apiFetch } from "@/lib/api-fetch";

const LABELS: Record<string, string> = { expiredReservations: "Expired Reservations", failedPayments: "Failed Payments", failedEmails: "Failed Emails", suspendedSellers: "Suspended Sellers", moderatedForumItems: "Moderated Forum Items" };
type Item = { id: string; title: string; detail: string; changedAt: string; acknowledged: boolean; acknowledgedAt: string | null; acknowledgedBy: string | null };

function Content() {
  const params = useSearchParams(); const queue = params.get("queue") || "expiredReservations";
  const [items, setItems] = React.useState<Item[]>([]); const [view, setView] = React.useState<"active" | "acknowledged" | "all">("active"); const [error, setError] = React.useState<string | null>(null); const [busy, setBusy] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { setError(null); const res = await fetch(`/api/admin/reviewable-attention?queue=${encodeURIComponent(queue)}`, { cache: "no-store" }); const data = await res.json(); if (!res.ok || !data?.ok) { setError(data?.error || "Could not load queue."); return; } setItems(data.items || []); }, [queue]);
  React.useEffect(() => { load(); }, [load]);
  async function acknowledge(itemId: string) { setBusy(itemId); setError(null); try { const res = await apiFetch("/api/admin/reviewable-attention", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ queue, itemId }) }); const data = await res.json(); if (!res.ok || !data?.ok) throw new Error(data?.error || "Could not acknowledge item."); await load(); } catch (err: any) { setError(err?.message || "Could not acknowledge item."); } finally { setBusy(null); } }
  const visible = items.filter((item) => view === "all" || (view === "active" ? !item.acknowledged : item.acknowledged));
  return <main style={{ maxWidth: 980, margin: "40px auto", padding: 16 }}><h1 style={{ margin: 0, fontSize: 28, fontWeight: 950 }}>Admin — {LABELS[queue] || "Reviewable Attention"}</h1><p style={{ opacity: .72 }}>Review these records, acknowledge those that need no further action, and retrieve them later from history.</p><Link href="/admin/tickets/verification" style={{ textDecoration: "underline" }}>← Back to Admin Queue</Link><div style={{ display: "flex", gap: 8, margin: "18px 0" }}>{(["active", "acknowledged", "all"] as const).map((option) => <button key={option} onClick={() => setView(option)} style={{ padding: "9px 12px", borderRadius: 999, border: "1px solid #ddd", background: view === option ? "#064a93" : "white", color: view === option ? "white" : "inherit", fontWeight: 800, textTransform: "capitalize" }}>{option}</button>)}</div>{error ? <div role="alert" style={{ padding: 10, background: "#fef2f2", color: "#991b1b" }}>{error}</div> : null}<div style={{ display: "grid", gap: 10 }}>{visible.map((item) => <section key={item.id} style={{ padding: 14, borderRadius: 10, border: "1px solid rgba(245,158,11,.4)", background: "#fffbeb", opacity: item.acknowledged ? .7 : 1 }}><strong>{item.title}</strong><div style={{ marginTop: 5 }}>{item.detail}</div><div style={{ marginTop: 5, fontSize: 12, opacity: .68 }}>Last changed {new Date(item.changedAt).toLocaleString()}</div>{item.acknowledged ? <div style={{ marginTop: 8, fontSize: 13 }}>Acknowledged {item.acknowledgedAt ? new Date(item.acknowledgedAt).toLocaleString() : ""}{item.acknowledgedBy ? ` by ${item.acknowledgedBy}` : ""}</div> : <button onClick={() => acknowledge(item.id)} disabled={busy === item.id} style={{ marginTop: 10, padding: "9px 12px", border: 0, borderRadius: 8, background: "#064a93", color: "white", fontWeight: 900 }}>{busy === item.id ? "Saving…" : "Acknowledge — remove from attention count"}</button>}</section>)}</div>{!visible.length ? <div style={{ padding: 24, border: "1px solid #ddd", borderRadius: 10 }}>No records in this view.</div> : null}</main>;
}
export default function Page() { return <React.Suspense fallback={<main style={{ padding: 40 }}>Loading…</main>}><Content /></React.Suspense>; }
