export type SiteLanguage = "en" | "fr";

export const LANGUAGE_STORAGE_KEY = "truefantix-language";
export const LANGUAGE_COOKIE = "tft_language";

export const frenchText: Record<string, string> = {
  "Home": "Accueil",
  "Tickets": "Billets",
  "Forum": "Forum",
  "Account": "Compte",
  "Profile": "Profil",
  "Change password": "Modifier le mot de passe",
  "Notifications": "Notifications",
  "Transaction history": "Historique des transactions",
  "My tickets": "Mes billets",
  "Verify": "Vérifier",
  "Login": "Connexion",
  "Log in": "Se connecter",
  "Log out": "Se déconnecter",
  "Logging out...": "Déconnexion...",
  "Create account": "Créer un compte",
  "Back": "Retour",
  "Checking session…": "Vérification de la session…",
  "Not signed in": "Non connecté",
  "Signed in as": "Connecté en tant que",
  "not verified": "non vérifié",
  "Action required": "Action requise",
  "Resolve now →": "Régler maintenant →",
  "Search": "Rechercher",
  "Search tickets": "Rechercher des billets",
  "Buy tickets": "Acheter des billets",
  "Sell tickets": "Vendre des billets",
  "Buy Tickets": "Acheter des billets",
  "Sell Tickets": "Vendre des billets",
  "Learn more": "En savoir plus",
  "View details": "Voir les détails",
  "Continue": "Continuer",
  "Cancel": "Annuler",
  "Save": "Enregistrer",
  "Submit": "Soumettre",
  "Confirm": "Confirmer",
  "Close": "Fermer",
  "Edit": "Modifier",
  "Delete": "Supprimer",
  "Loading...": "Chargement...",
  "Loading…": "Chargement…",
  "Email": "Courriel",
  "Email address": "Adresse courriel",
  "Password": "Mot de passe",
  "First name": "Prénom",
  "Last name": "Nom de famille",
  "Phone": "Téléphone",
  "City": "Ville",
  "Province": "Province",
  "Country": "Pays",
  "Price": "Prix",
  "Quantity": "Quantité",
  "Total": "Total",
  "Continue to checkout": "Passer à la caisse",
  "Checkout": "Paiement",
  "Order summary": "Sommaire de la commande",
  "Payment": "Paiement",
  "Payment method": "Mode de paiement",
  "Back to tickets": "Retour aux billets",
  "No tickets found": "Aucun billet trouvé",
  "Try again": "Réessayer",
  "Something went wrong": "Une erreur s’est produite",
  "Required": "Obligatoire",
  "Optional": "Facultatif",
  "Previous": "Précédent",
  "Next": "Suivant",
  "About": "À propos",
  "Our Story": "Notre histoire",
  "How It Works": "Fonctionnement",
  "Why Face Value": "Pourquoi le prix nominal",
  "Trust & Safety": "Confiance et sécurité",
  "Trust and Safety": "Confiance et sécurité",
  "Buying Tickets": "Acheter des billets",
  "Selling Tickets": "Vendre des billets",
  "Access Tokens": "Jetons d’accès",
  "Payments": "Paiements",
  "Refunds": "Remboursements",
  "Contact": "Nous joindre",
  "Email Us": "Nous écrire",
  "Report an Issue": "Signaler un problème",
  "Privacy Policy": "Politique de confidentialité",
  "Terms of Service": "Conditions d’utilisation",
  "Accessibility": "Accessibilité",
  "Community Guidelines": "Règles de la communauté",
  "All rights reserved.": "Tous droits réservés.",
  "© 2026 TrueFanTix. All rights reserved.": "© 2026 TrueFanTix. Tous droits réservés.",
  "Built for fans — not scalpers.": "Conçu pour les amateurs — pas pour les revendeurs.",
  "A fan-first ticket marketplace focused on fairness, transparency, and resale at or below face value.":
    "Une plateforme de billets pensée pour les amateurs, axée sur l’équité, la transparence et la revente au prix nominal ou moins.",
  "English": "English",
  "French": "Français",
  "Language": "Langue",
  "Select language": "Choisir la langue",
  "Settings": "Paramètres",
  "Security": "Sécurité",
  "Reviews": "Évaluations",
  "Bought": "Achetés",
  "Sold": "Vendus",
  "Selling": "En vente",
  "Holding": "En attente",
  "Forgot password?": "Mot de passe oublié?",
  "Reset password": "Réinitialiser le mot de passe",
  "Sign up": "S’inscrire",
  "Already have an account?": "Vous avez déjà un compte?",
  "Don't have an account?": "Vous n’avez pas de compte?",
  "Help": "Aide",
  "Frequently Asked Questions": "Foire aux questions",
  "Browse Tickets": "Parcourir les billets",
  "Find tickets at or below face value for your favorite events": "Trouvez des billets au prix nominal ou moins pour vos événements préférés",
  "List Tickets": "Mettre des billets en vente",
  "Featured Tickets": "Billets en vedette",
  "List Tickets for Sale": "Mettre des billets en vente",
  "Create your free account": "Créez votre compte gratuit",
  "Community Forum": "Forum communautaire",
  "TrueFanTix Community": "Communauté TrueFanTix",
  "Welcome to the TrueFanTix Community — You’re Here at the Beginning":
    "Bienvenue dans la communauté TrueFanTix — Vous êtes là depuis le début",
  "Welcome to the TrueFanTix Community — You're Here at the Beginning":
    "Bienvenue dans la communauté TrueFanTix — Vous êtes là depuis le début",
  "Discuss events, artists, teams, and shows with other fans.":
    "Discutez d’événements, d’artistes, d’équipes et de spectacles avec d’autres amateurs.",
  "View all discussions": "Voir toutes les discussions",
  "No discussions yet": "Aucune discussion pour le moment",
  "No discussions yet.": "Aucune discussion pour le moment.",
  "+ New Discussion": "+ Nouvelle discussion",
  "Sign in to participate in discussions": "Connectez-vous pour participer aux discussions",
  "Sign In": "Se connecter",
  "Start the first discussion →": "Lancer la première discussion →",
  "Pinned by Admin": "Épinglée par l’administrateur",
  "Want to join the conversation? Sign in to reply to posts and create new discussions.":
    "Vous voulez participer à la conversation? Connectez-vous pour répondre aux publications et créer de nouvelles discussions.",
  "Sign In to Participate": "Se connecter pour participer",
  "Thread not found": "Discussion introuvable",
  "Thread locked.": "Discussion verrouillée.",
  "No posts yet. Be the first to reply!": "Aucune publication pour le moment. Soyez le premier à répondre!",
  "Please log in to reply.": "Veuillez vous connecter pour répondre.",
  "Please verify your email and phone number to reply.": "Veuillez vérifier votre courriel et votre numéro de téléphone pour répondre.",
  "This account is restricted.": "Ce compte est restreint.",
  "This thread is locked.": "Cette discussion est verrouillée.",
  "Reply cannot be empty.": "La réponse ne peut pas être vide.",
  "Write your reply…": "Écrivez votre réponse…",
  "Write a new post…": "Rédigez une nouvelle publication…",
  "Cancel reply": "Annuler la réponse",
  "Posting...": "Publication...",
  "Post": "Publier",
  "Locked": "Verrouillée",
  "Photos": "Photos",
  "(optional, up to 3; 2 MB total)": "(facultatif, jusqu’à 3; 2 Mo au total)",
  "Loading latest discussions…": "Chargement des discussions récentes…",
  "Latest discussions (showing up to 6).": "Discussions récentes (jusqu’à 6 affichées).",
  "Select featured tickets to checkout directly.": "Choisissez des billets en vedette pour passer directement à la caisse.",
  "Limited-time launch promotion": "Promotion de lancement à durée limitée",
  "Create your free account and receive 4 access tokens. Sell tickets during the promotion and earn an additional 4 access tokens for every ticket sold.":
    "Créez votre compte gratuit et recevez 4 jetons d’accès. Vendez des billets pendant la promotion et obtenez 4 jetons d’accès supplémentaires pour chaque billet vendu.",
  "Welcome to": "Bienvenue sur",
  "Buy and sell tickets at or below face value. Secure, fair, and fan-first.": "Achetez et vendez des billets au prix nominal ou moins. Sécuritaire, équitable et pensé pour les amateurs.",
  "Could not load tickets": "Impossible de charger les billets",
  "Loading tickets...": "Chargement des billets...",
  "No tickets match your search.": "Aucun billet ne correspond à votre recherche.",
  "All Event Types": "Tous les types d’événements",
  "Any Price": "Tous les prix",
  "Any Price Type": "Tous les types de prix",
  "Face Value": "Prix nominal",
  "Start date": "Date de début",
  "End date": "Date de fin",
  "Concert": "Concert",
  "Comedy": "Humour",
  "Conference": "Conférence",
  "Festival": "Festival",
  "Theatre": "Théâtre",
  "Opera": "Opéra",
  "Other": "Autre",
  "Sports: Baseball": "Sports : baseball",
  "Sports: Basketball": "Sports : basketball",
  "Sports: Football": "Sports : football",
  "Sports: Hockey": "Sports : hockey",
  "Sports: Lacrosse": "Sports : crosse",
  "Sports: Soccer": "Sports : soccer",
  "Sports: Other": "Sports : autre",
  "Search events, venues, artists, teams, shows, towns or cities...": "Rechercher des événements, salles, artistes, équipes, spectacles, villes ou municipalités...",
  "Within": "Dans un rayon de",
  "Unit": "Unité",
  "miles": "milles",
  "Under $50": "Moins de 50 $",
  "⭐ Sold Out Events Only": "⭐ Événements à guichets fermés seulement",
  "Clear Filters": "Réinitialiser les filtres",
  "Select visible": "Sélectionner les billets visibles",
  "Clear visible": "Désélectionner les billets visibles",
  "Clear selection": "Effacer la sélection",
  "Checkout selected": "Passer à la caisse avec la sélection",
  "Preparing checkout...": "Préparation du paiement...",
  "Retry": "Réessayer",
  "Your identity and verification status.": "Votre identité et votre état de vérification.",
  "✓ verified": "✓ vérifié",
  "• not verified": "• non vérifié",
  "Verified": "Vérifié",
  "Not verified yet": "Pas encore vérifié",
  "Edit profile": "Modifier le profil",
  "Update name, phone, display name, and contact preferences.": "Modifiez votre nom, votre téléphone, votre nom affiché et vos préférences de communication.",
  "Manage verification": "Gérer la vérification",
  "Verify email/phone and complete any remaining checks.": "Vérifiez votre courriel et votre téléphone, puis terminez les vérifications restantes.",
  "Seller verification": "Vérification du vendeur",
  "Required before you can list tickets. This protects buyers and unlocks payouts.": "Obligatoire avant de pouvoir mettre des billets en vente. Cette étape protège les acheteurs et débloque les versements.",
  "Email verified": "Courriel vérifié",
  "Phone verified": "Téléphone vérifié",
  "Identity + payouts (Stripe)": "Identité et versements (Stripe)",
  "Identity + payouts (Stripe) • checking…": "Identité et versements (Stripe) • vérification…",
  "You’re approved to sell.": "Vous êtes autorisé à vendre.",
  "Complete verification to unlock selling (identity + payouts is handled through Stripe).": "Terminez la vérification pour pouvoir vendre (l’identité et les versements sont gérés par Stripe).",
  "Seller verified": "Vendeur vérifié",
  "Starting verification…": "Démarrage de la vérification…",
  "Verify email + phone first": "Vérifiez d’abord le courriel et le téléphone",
  "Start seller verification": "Commencer la vérification du vendeur",
  "Refresh Stripe status": "Actualiser l’état Stripe",
  "Opening Stripe…": "Ouverture de Stripe…",
  "Manage Stripe account": "Gérer le compte Stripe",
  "Manage email/phone verification": "Gérer la vérification du courriel et du téléphone",
  "We’ll never show your private identity details to buyers. Stripe is used only for identity checks and payouts.": "Nous ne montrerons jamais vos renseignements d’identité privés aux acheteurs. Stripe sert uniquement aux vérifications d’identité et aux versements.",
  "Stripe sometimes takes a moment to enable capabilities after onboarding. If this doesn’t turn green, click": "Stripe peut prendre un moment pour activer les fonctions après l’inscription. Si cet indicateur ne devient pas vert, cliquez sur",
  "Seller payout speed": "Vitesse des versements au vendeur",
  "See how your payouts are currently delivered and how to qualify for faster delivery.": "Voyez comment vos versements sont actuellement acheminés et comment obtenir un versement plus rapide.",
  "Your current setup": "Votre configuration actuelle",
  "✓ Fast payouts enabled": "✓ Versements rapides activés",
  "Standard payouts enabled": "Versements standards activés",
  "Payout destination setup required": "Configuration de la destination de versement requise",
  "Stripe has verified an eligible debit card. After the buyer confirms receipt, your proceeds are sent by Instant Payout and normally arrive within 30 minutes.": "Stripe a vérifié une carte de débit admissible. Après la confirmation de réception par l’acheteur, votre produit de vente est envoyé par versement instantané et arrive normalement dans les 30 minutes.",
  "Stripe has a bank account for you, but it only supports standard delivery. After the buyer confirms receipt, TrueFanTix releases your proceeds immediately to Stripe; Stripe then deposits them according to its standard payout schedule.": "Stripe dispose de votre compte bancaire, mais celui-ci accepte uniquement les versements standards. Après la confirmation de réception par l’acheteur, TrueFanTix remet immédiatement votre produit de vente à Stripe, qui le dépose ensuite selon son calendrier de versement standard.",
  "Stripe has not found a valid payout destination yet. Add a bank account for standard payouts or an eligible debit card for fast payouts.": "Stripe n’a pas encore trouvé de destination de versement valide. Ajoutez un compte bancaire pour les versements standards ou une carte de débit admissible pour les versements rapides.",
  "Standard payout": "Versement standard",
  "Fast payout": "Versement rapide",
  "Uses your bank account. TrueFanTix releases the money when the buyer confirms receipt, but Stripe’s standard processing schedule determines when it reaches your bank.": "Utilise votre compte bancaire. TrueFanTix libère l’argent lorsque l’acheteur confirme la réception, mais le calendrier de traitement standard de Stripe détermine quand il arrive dans votre compte.",
  "Requires a Stripe-eligible debit card. After the buyer confirms receipt, proceeds are sent by Instant Payout and normally reach the linked account within 30 minutes.": "Nécessite une carte de débit admissible auprès de Stripe. Après la confirmation de réception par l’acheteur, le produit de vente est envoyé par versement instantané et atteint normalement le compte lié dans les 30 minutes.",
  "TrueFanTix currently pays Stripe’s 1% Instant Payout fee, so the fee is not deducted from your ticket proceeds. Stripe decides whether a debit card is eligible.": "TrueFanTix paie actuellement les frais de 1 % de Stripe pour les versements instantanés; ces frais ne sont donc pas déduits du produit de vos billets. Stripe détermine l’admissibilité des cartes de débit.",
  "Recheck eligibility": "Revérifier l’admissibilité",
  "Add eligible debit card in Stripe": "Ajouter une carte de débit admissible dans Stripe",
  "Account tools": "Outils du compte",
  "Everything you can manage from your account.": "Tout ce que vous pouvez gérer à partir de votre compte.",
  "Access token balance:": "Solde de jetons d’accès :",
  "Update your password and security settings.": "Modifiez votre mot de passe et vos paramètres de sécurité.",
  "Choose alerts for artists, teams, venues, and sold-out opportunities.": "Choisissez des alertes pour les artistes, les équipes, les salles et les occasions à guichets fermés.",
  "See purchases, sales, payouts, refunds, and access tokens.": "Consultez vos achats, ventes, versements, remboursements et jetons d’accès.",
  "See reviews you’ve left, reviews you’ve received, and purchases waiting for your review.": "Consultez les évaluations que vous avez laissées ou reçues et les achats en attente de votre évaluation.",
  "Review needed": "Évaluation requise",
  "Quick access to tickets you’re holding, selling, or have completed.": "Accès rapide aux billets que vous détenez, vendez ou avez traités.",
  "Checkout incomplete": "Paiement incomplet",
  "Payment has not been completed yet. Finish checkout or let the reservation expire before treating these tickets as bought.": "Le paiement n’est pas encore terminé. Terminez-le ou laissez la réservation expirer avant de considérer ces billets comme achetés.",
  "Payment required": "Paiement requis",
  "Holding (incoming / transferred to you)": "Billets détenus (entrants ou transférés à vous)",
  "Transferred tickets are waiting for you to confirm receipt.": "Des billets transférés attendent votre confirmation de réception.",
  "Tickets you bought are still active until transfer and final completion.": "Les billets achetés demeurent actifs jusqu’au transfert et à la finalisation.",
  "Tickets you bought that are not yet delivered or are in your possession.": "Billets achetés qui ne sont pas encore livrés ou qui sont en votre possession.",
  "Active tickets": "Billets actifs",
  "Selling (active listings)": "En vente (annonces actives)",
  "Tickets currently available for sale.": "Billets actuellement offerts à la vente.",
  "Tickets currently listed for sale.": "Billets actuellement mis en vente.",
  "Locked until seller verification is complete (email + phone + Stripe).": "Verrouillé jusqu’à ce que la vérification du vendeur soit terminée (courriel, téléphone et Stripe).",
  "Active listings": "Annonces actives",
  "Seller holding (transfer required)": "Billets vendus détenus (transfert requis)",
  "Sold tickets need transfer proof before the deadline.": "Les billets vendus nécessitent une preuve de transfert avant l’échéance.",
  "Sold tickets are awaiting buyer confirmation or final completion.": "Les billets vendus attendent la confirmation de l’acheteur ou la finalisation.",
  "Sold tickets awaiting transfer or buyer confirmation.": "Billets vendus en attente de transfert ou de confirmation de l’acheteur.",
  "Transfer required": "Transfert requis",
  "In progress": "En cours",
  "Bought (completed)": "Achetés (terminés)",
  "Completed purchases for upcoming events.": "Achats terminés pour des événements à venir.",
  "Your past purchases and receipts.": "Vos achats et reçus antérieurs.",
  "Upcoming event": "Événement à venir",
  "Sold (completed)": "Vendus (terminés)",
  "Your past sales and payout records.": "Vos ventes et relevés de versement antérieurs.",
  "Danger zone": "Zone dangereuse",
  "Destructive actions. These cannot be undone.": "Actions destructives. Elles sont irréversibles.",
  "Delete account": "Supprimer le compte",
  "This permanently deletes your account and logs you out. For safety, you must confirm with your password.": "Cette action supprime définitivement votre compte et vous déconnecte. Par sécurité, vous devez confirmer avec votre mot de passe.",
  "Type DELETE to confirm": "Tapez DELETE pour confirmer",
  "Type": "Tapez",
  "to confirm": "pour confirmer",
  "Type \"DELETE\"": "Tapez « DELETE »",
  "Deleting…": "Suppression…",
  "Delete my account": "Supprimer mon compte",
  "Loading account...": "Chargement du compte...",
  "Create an account": "Créer un compte",
  "Email or phone": "Courriel ou téléphone",
  "Use your email or phone number.": "Utilisez votre courriel ou votre numéro de téléphone.",
  "Confirm password": "Confirmer le mot de passe",
  "Display name (optional)": "Nom affiché (facultatif)",
  "Postal / ZIP": "Code postal / ZIP",
  "Province / State": "Province / État",
  "Street address": "Adresse",
  "Street address 2 (optional)": "Complément d’adresse (facultatif)",
  "United States": "États-Unis",
  "Overall verification": "Vérification générale",
  "Report issue": "Signaler un problème",
  "Send": "Envoyer",
  "Reply": "Répondre",
  "New post": "Nouvelle publication",
  "New thread": "Nouvelle discussion",
  "Post reply": "Publier la réponse",
  "Updated": "Mis à jour",
  "reply": "réponse",
  "replies": "réponses",

  // Public informational pages reached from the header, footer, and page-to-page links.
  "How it Works": "Fonctionnement",
  "TrueFanTix is different from traditional resale platforms": "TrueFanTix se distingue des plateformes de revente traditionnelles",
  "For Sellers": "Pour les vendeurs",
  "List tickets at or below face value": "Mettez vos billets en vente au prix nominal ou moins",
  "Set your price at or below what you originally paid (including fees)": "Fixez votre prix au montant que vous avez payé à l’origine (frais compris) ou à un montant inférieur",
  "Keep tickets ready for secure buyer transfer": "Gardez les billets prêts pour un transfert sécurisé à l’acheteur",
  "Your tickets stay with your original ticket provider until they sell. Once there's a buyer, we guide the transfer and hold payment until delivery is confirmed.": "Vos billets restent chez votre fournisseur d’origine jusqu’à leur vente. Lorsqu’un acheteur se présente, nous encadrons le transfert et retenons le paiement jusqu’à la confirmation de la livraison.",
  "Once sold and delivered successfully, receive 100% of your ticket price": "Une fois les billets vendus et livrés, recevez 100 % de leur prix",
  "No seller fees - you keep the full amount": "Aucuns frais pour le vendeur — vous conservez le montant intégral",
  "Earn access tokens for sold out events": "Gagnez des jetons d’accès pour les événements à guichets fermés",
  "If tickets sold were for a sold out event, you receive 100% of your ticket price and you earn access tokens to purchase an equivalent amount of tickets to any other sold out events of your choosing, whenever you choose to use them. The access tokens never expire. Your access token balance only gets drawn down as you use them to purchase tickets to sold out events.": "Si les billets vendus étaient pour un événement à guichets fermés, vous recevez 100 % de leur prix et gagnez des jetons d’accès permettant d’acheter un nombre équivalent de billets pour d’autres événements à guichets fermés de votre choix. Les jetons n’expirent jamais et votre solde diminue seulement lorsque vous les utilisez.",
  "Non-sold out events": "Événements qui ne sont pas à guichets fermés",
  "If tickets sold were for an event that was not sold out, you receive 100% of your ticket price.": "Si les billets vendus étaient pour un événement qui n’était pas à guichets fermés, vous recevez 100 % de leur prix.",
  "Why sell tickets below face value?": "Pourquoi vendre des billets sous le prix nominal?",
  "If the event isn't sold out, it makes it less likely that buyers will choose your tickets over the original seller unless you reduce your price. Secondary Ticket Market Places charge fees for selling tickets. We believe, we have the lowest admin fees out there, and the seller doesn't pay them, the buyer does.": "Si l’événement n’est pas à guichets fermés, les acheteurs risquent de préférer le vendeur d’origine à moins que vous réduisiez votre prix. Les marchés secondaires imposent des frais de vente. Nous croyons offrir parmi les frais administratifs les plus bas, payés par l’acheteur plutôt que par le vendeur.",
  "Build reputation through successful transactions": "Bâtissez votre réputation grâce à des transactions réussies",
  "Each sale builds your reputation as a trusted seller": "Chaque vente renforce votre réputation de vendeur digne de confiance",
  "There are no hidden seller fees. Sellers are kept whole.": "Il n’y a aucuns frais cachés pour les vendeurs. Ils reçoivent le montant intégral.",
  "For Buyers": "Pour les acheteurs",
  "Browse verified listings": "Parcourez les annonces vérifiées",
  "Listings are reviewed for ticket evidence, event details, and face-value pricing rules": "Les annonces sont vérifiées selon les preuves du billet, les détails de l’événement et les règles de prix nominal",
  "All tickets are priced at or below face value": "Tous les billets sont au prix nominal ou moins",
  "You'll never pay more than the original buyer": "Vous ne paierez jamais plus que l’acheteur d’origine",
  "For Events that Aren't Sold Out:": "Pour les événements qui ne sont pas à guichets fermés :",
  "Anyone can purchase tickets to any event that is not sold out.": "Tout le monde peut acheter des billets pour un événement qui n’est pas à guichets fermés.",
  "For Sold Out Events Only": "Pour les événements à guichets fermés seulement",
  "Only buyers with access tokens will have access to purchase tickets to sold out events. To earn access tokens to sold out events, you must first sell tickets to sold out events. Each sold out event ticket sold earns one access token. Each access token provides access to purchase 1 sold out event ticket.": "Seuls les acheteurs possédant des jetons d’accès peuvent acheter des billets pour les événements à guichets fermés. Pour gagner ces jetons, vous devez d’abord vendre des billets pour un tel événement. Chaque billet vendu donne un jeton, qui permet d’acheter un billet pour un événement à guichets fermés.",
  "Pay ticket price + 8.75% admin fee ($5.00 minimum per order)": "Payez le prix du billet plus des frais administratifs de 8,75 % (minimum de 5,00 $ par commande)",
  "TrueFanTix is not currently collecting tax on the admin fee. Most of the admin fee goes toward paying for the services required to run the site.": "TrueFanTix ne perçoit actuellement aucune taxe sur les frais administratifs. La majeure partie de ces frais sert à payer les services nécessaires au fonctionnement du site.",
  "Receive tickets through a secure seller transfer": "Recevez les billets au moyen d’un transfert sécurisé du vendeur",
  "The seller transfers tickets to you after purchase, and your payment stays protected until delivery is confirmed.": "Le vendeur vous transfère les billets après l’achat, et votre paiement demeure protégé jusqu’à la confirmation de la livraison.",
  "Every transaction is protected by verification, duplicate prevention, and dispute resolution workflows.": "Chaque transaction est protégée par des processus de vérification, de prévention des doublons et de règlement des différends.",
  "Next: Why Face Value →": "Suivant : pourquoi le prix nominal →",

  "Built by a fan, for fans": "Créé par un amateur, pour les amateurs",
  "TrueFanTix was built on a simple belief: Fans shouldn't be priced out of the events they love.": "TrueFanTix repose sur une conviction simple : le prix ne devrait pas empêcher les amateurs d’assister aux événements qu’ils aiment.",
  "I built TrueFanTix because I am a fan like you.": "J’ai créé TrueFanTix parce que je suis un amateur comme vous.",
  "Like many of you, I have watched tickets go on sale at a list price, only to see them reappear minutes later on secondary sites for two, three, even four times more. I have sat in countless online queues, refreshed screens, coming to the full realization that the system was never designed for actual fans, it was designed for quick profit.": "Comme beaucoup d’entre vous, j’ai vu des billets mis en vente au prix affiché réapparaître quelques minutes plus tard sur des sites secondaires à deux, trois ou même quatre fois ce prix. Après d’innombrables files d’attente en ligne et actualisations d’écran, j’ai compris que le système n’avait jamais été conçu pour les vrais amateurs, mais pour le profit rapide.",
  "I'm part of the community that has felt the problem and wanted to do something about it.": "Je fais partie de la communauté qui a vécu ce problème et qui voulait agir.",
  "I have loved attending live events since I was a teenager. I've had so many great memories over the years, some of which will last a lifetime. Everything was so much simpler back then. Sure, there were usually scalpers standing outside of venues, but they didn't seem to have much of an impact on our experience. Nothing like we see today.": "J’adore assister à des événements en personne depuis mon adolescence. J’en garde de merveilleux souvenirs, dont certains pour toute la vie. Tout était beaucoup plus simple à l’époque. Il y avait bien des revendeurs devant les salles, mais leur effet sur notre expérience n’avait rien à voir avec ce que nous voyons aujourd’hui.",
  "Scalping has transformed into large-scale flipping operations that has become big business at the cost of actual fans. Tickets intended for true fans are treated like commodities to be flipped. Buy low, sell high. Prices have skyrocketed. The trust in the system is long gone. And the actual fans, the very people these events are made for are often left out.": "La revente est devenue une activité à grande échelle et lucrative aux dépens des vrais amateurs. Les billets qui leur sont destinés sont traités comme des marchandises : acheter à bas prix, revendre à prix fort. Les prix ont explosé, la confiance a disparu et les amateurs pour qui ces événements existent sont souvent laissés de côté.",
  "TrueFanTix was created to offer an alternative to the current system. There will never be any scalpers here. If you're here because you've felt the same frustration, you're not alone. And you're exactly who this platform is built for.": "TrueFanTix a été créé pour offrir une solution de rechange au système actuel. Il n’y aura jamais de revendeurs abusifs ici. Si vous avez ressenti la même frustration, vous n’êtes pas seul : cette plateforme est précisément faite pour vous.",
  "Founder, TrueFanTix": "Fondateur, TrueFanTix",
  "Next: How It Works →": "Suivant : fonctionnement →",

  "One core rule: Tickets at or below face value": "Une règle fondamentale : les billets au prix nominal ou moins",
  "TrueFanTix enforces one core rule: Tickets must be listed at or below face value (including original fees).": "TrueFanTix applique une règle fondamentale : les billets doivent être affichés au prix nominal ou moins, frais d’origine compris.",
  "Why?": "Pourquoi?",
  "Because live events are experiences for real fans, not commodities for price manipulation.": "Parce que les événements en personne sont des expériences pour de vrais amateurs, et non des marchandises dont on manipule le prix.",
  "By enforcing face value:": "En imposant le prix nominal :",
  "We reduce speculative buying (scalping)": "Nous réduisons l’achat spéculatif (revente abusive)",
  "No more buying tickets just to resell at higher prices.": "Fini l’achat de billets dans le seul but de les revendre plus cher.",
  "We serve genuine fans": "Nous servons les vrais amateurs",
  "Tickets go to people who actually want to attend.": "Les billets vont aux personnes qui veulent réellement assister à l’événement.",
  "We create a community": "Nous créons une communauté",
  "A place for like-minded individuals who love live events.": "Un lieu pour les personnes qui partagent l’amour des événements en personne.",
  "Alternative to buy low, sell high": "Une solution de rechange au modèle acheter à bas prix, revendre à prix fort",
  "Breaking the traditional resale model.": "Nous brisons le modèle traditionnel de revente.",
  "We build long-term trust": "Nous bâtissons une confiance durable",
  "Through you and with you.": "Grâce à vous et avec vous.",
  "This is not about limiting sellers. It's about creating a place for like minded fans that are tired of the way the current system is failing them. We prioritize fairness and access over exploitation.": "Il ne s’agit pas de limiter les vendeurs, mais de créer un lieu pour les amateurs qui en ont assez d’un système qui les laisse tomber. Nous privilégions l’équité et l’accès plutôt que l’exploitation.",
  "Price Transparency": "Transparence des prix",
  "Transparency badges clearly display:": "Des indicateurs de transparence affichent clairement :",
  "At Face Value": "Au prix nominal",
  "Below Face Value": "Sous le prix nominal",
  "No guessing. No hidden markups.": "Aucune ambiguïté. Aucune majoration cachée.",
  "Next: Trust & Safety →": "Suivant : confiance et sécurité →",

  "Trust is built into the platform": "La confiance est intégrée à la plateforme",
  "Payment Protection": "Protection des paiements",
  "TrueFanTix does not take custody of tickets before listing. Sellers keep tickets with their original ticket provider until a purchase is made, and buyer payment is protected until delivery is confirmed.": "TrueFanTix ne prend pas possession des billets avant leur mise en vente. Les vendeurs les conservent chez leur fournisseur d’origine jusqu’à l’achat, et le paiement de l’acheteur est protégé jusqu’à la confirmation de la livraison.",
  "Payment hold": "Retenue du paiement",
  "Sellers are not paid until ticket delivery is confirmed": "Les vendeurs ne sont payés qu’après la confirmation de la livraison des billets",
  "Transfer tracking": "Suivi du transfert",
  "Sellers submit transfer proof and buyers confirm receipt": "Les vendeurs fournissent une preuve de transfert et les acheteurs confirment la réception",
  "Dispute pause": "Suspension en cas de différend",
  "Payouts are paused if a buyer reports a delivery issue": "Les versements sont suspendus si un acheteur signale un problème de livraison",
  "Verification": "Vérification",
  "We verify listings and transactions in layers:": "Nous vérifions les annonces et les transactions à plusieurs niveaux :",
  "Seller and account checks": "Vérification du vendeur et du compte",
  "Sellers must use a verified account before listing tickets": "Les vendeurs doivent utiliser un compte vérifié avant d’afficher des billets",
  "Listing evidence review": "Examen des preuves de l’annonce",
  "We check listing details, receipt evidence, event information, and face-value pricing rules": "Nous vérifions les détails de l’annonce, la preuve d’achat, les renseignements sur l’événement et le respect du prix nominal",
  "Delivery confirmation": "Confirmation de la livraison",
  "Sellers provide transfer proof, buyers confirm receipt, and our team reviews edge cases or disputes": "Les vendeurs fournissent une preuve de transfert, les acheteurs confirment la réception et notre équipe examine les cas particuliers ou les différends",
  "Seller Reputation": "Réputation du vendeur",
  "Each seller builds a public reputation score based on:": "Chaque vendeur bâtit une réputation publique fondée sur :",
  "Buyer reviews": "Évaluations des acheteurs",
  "Feedback from every transaction": "Commentaires liés à chaque transaction",
  "Successful deliveries": "Livraisons réussies",
  "Track record of completed sales": "Historique des ventes conclues",
  "Dispute history": "Historique des différends",
  "How issues were resolved": "Façon dont les problèmes ont été réglés",
  "Dispute Resolution": "Règlement des différends",
  "If a buyer opens a dispute:": "Si un acheteur ouvre un différend :",
  "Seller payout is paused": "Le versement au vendeur est suspendu",
  "- No money changes hands until resolved": "— Aucun argent n’est versé avant le règlement",
  "Evidence is reviewed": "Les preuves sont examinées",
  "- Both parties can submit documentation": "— Les deux parties peuvent fournir des documents",
  "Admin resolves fairly": "L’administration tranche équitablement",
  "- Impartial decision based on evidence": "— Une décision impartiale est prise selon les preuves",
  "We combine": "Nous combinons",
  "automation": "l’automatisation",
  "with": "avec",
  "human oversight": "la supervision humaine",
  "to maintain marketplace integrity.": "pour préserver l’intégrité de la plateforme.",
  "Next: FAQ →": "Suivant : FAQ →",

  "Find answers to common questions about TrueFanTix": "Trouvez des réponses aux questions fréquentes sur TrueFanTix",
  "Learn about purchasing tickets, access tokens for sold out events, and buyer fees.": "Renseignez-vous sur l’achat de billets, les jetons d’accès aux événements à guichets fermés et les frais d’acheteur.",
  "How to list tickets, when to sell below face value, payouts, and seller fees.": "Découvrez comment afficher des billets, quand vendre sous le prix nominal, ainsi que les versements et les frais de vendeur.",
  "Understanding the access token system for sold out events.": "Comprenez le système de jetons d’accès aux événements à guichets fermés.",
  "How payments work, Stripe Connect, currencies, and admin fees.": "Découvrez le fonctionnement des paiements, Stripe Connect, les devises et les frais administratifs.",
  "Refund policies for cancellations, delivery issues, and disputes.": "Consultez les politiques de remboursement en cas d’annulation, de problème de livraison ou de différend.",
  "Next: Terms of Service →": "Suivant : conditions d’utilisation →",

  "Are ticket prices fair?": "Les prix des billets sont-ils équitables?",
  "Yes, they absolutely are. Tickets can only be listed on this site at or below their original cost.": "Oui, absolument. Les billets peuvent seulement être affichés au prix d’origine ou moins.",
  "Do I need access tokens to purchase tickets to events that aren't sold out?": "Ai-je besoin de jetons d’accès pour acheter des billets pour un événement qui n’est pas à guichets fermés?",
  "No. Anyone can purchase tickets to shows that aren't sold out.": "Non. Tout le monde peut acheter des billets pour un spectacle qui n’est pas à guichets fermés.",
  "Do I need access tokens to purchase tickets to events that are sold out?": "Ai-je besoin de jetons d’accès pour acheter des billets pour un événement à guichets fermés?",
  "Yes. You need to use one access token for each ticket purchased for a sold out event.": "Oui. Vous devez utiliser un jeton d’accès pour chaque billet acheté pour un événement à guichets fermés.",
  "Yes. You need to use one access token for each ticket purchased for a sold out event. See": "Oui. Vous devez utiliser un jeton d’accès pour chaque billet acheté pour un événement à guichets fermés. Consultez la",
  "access tokens FAQ": "FAQ sur les jetons d’accès",
  "for more information.": "pour en savoir plus.",
  "Are tickets guaranteed?": "Les billets sont-ils garantis?",
  "Listings are reviewed before they go live, seller payment is held until delivery is confirmed, and disputes pause payout while our team reviews the evidence.": "Les annonces sont examinées avant leur publication, le paiement au vendeur est retenu jusqu’à la confirmation de la livraison et tout différend suspend le versement pendant l’examen des preuves.",
  "Will I receive the exact tickets listed?": "Vais-je recevoir exactement les billets affichés?",
  "Yes. Listings cannot be substituted without approval.": "Oui. Les billets d’une annonce ne peuvent être remplacés sans approbation.",
  "What fees do I pay as a buyer?": "Quels frais dois-je payer comme acheteur?",
  "You pay:": "Vous payez :",
  "Ticket price": "Prix du billet",
  "8.75% admin fee ($5.00 minimum per order)": "Frais administratifs de 8,75 % (minimum de 5,00 $ par commande)",
  "TrueFanTix is not currently collecting tax on the admin fee. All fees are shown clearly at checkout.": "TrueFanTix ne perçoit actuellement aucune taxe sur les frais administratifs. Tous les frais sont clairement indiqués au paiement.",
  "Can I review a seller?": "Puis-je évaluer un vendeur?",
  "Yes. After purchase, buyers can leave reviews and ratings.": "Oui. Après l’achat, les acheteurs peuvent laisser une évaluation et une note.",
  "Next: Selling Tickets →": "Suivant : vendre des billets →",

  "Why should I sell tickets to events that are sold out on this site?": "Pourquoi devrais-je vendre ici des billets pour un événement à guichets fermés?",
  "By selling tickets to sold out events on this site, you gain access to purchase tickets to events that are sold out at or below face value. TrueFanTix is designed to be a community that benefits actual fans.": "En vendant ici des billets pour des événements à guichets fermés, vous obtenez la possibilité d’acheter des billets pour d’autres événements à guichets fermés au prix nominal ou moins. TrueFanTix est une communauté conçue au bénéfice des vrais amateurs.",
  "Why should I sell tickets to events that aren't sold out on this site?": "Pourquoi devrais-je vendre ici des billets pour un événement qui n’est pas à guichets fermés?",
  "The fees paid by the buyer on this site are very low compared to other secondary market sites which benefits the purchaser while providing the seller 100% of their list price. Many other sites charge fees to the seller, but this site does not.": "Les frais payés par l’acheteur sont très bas comparativement à ceux d’autres marchés secondaires. L’acheteur en profite et le vendeur reçoit 100 % du prix affiché. Beaucoup d’autres sites imposent des frais au vendeur; pas celui-ci.",
  "Do I pay fees to sell tickets?": "Dois-je payer des frais pour vendre des billets?",
  "No the seller doesn't pay any fees to sell on this site. Sellers receive 100% of their listed ticket price.": "Non. Le vendeur ne paie aucuns frais pour vendre sur ce site et reçoit 100 % du prix affiché.",
  "Can I list above face value?": "Puis-je afficher un prix supérieur au prix nominal?",
  "No. Tickets must be listed at or below face value but includes any original fees paid by the seller (i.e. Ticketmaster fees). The TrueFanTix system is meant to be fair. Our aim is to keep sellers whole and rewarding them with access to sold out events at face value prices.": "Non. Les billets doivent être affichés au prix nominal ou moins, en incluant les frais d’origine payés par le vendeur (par exemple, les frais Ticketmaster). TrueFanTix vise l’équité : le vendeur reçoit le montant intégral et obtient un accès aux événements à guichets fermés au prix nominal.",
  "When should I sell my tickets for less than face value?": "Quand devrais-je vendre mes billets sous le prix nominal?",
  "If an event is not sold out, you may want to consider selling your tickets for below face value as an incentive to purchasers to buy your tickets instead of someone else's.": "Si un événement n’est pas à guichets fermés, vous pourriez vendre vos billets sous le prix nominal afin d’inciter les acheteurs à les choisir plutôt que ceux d’une autre personne.",
  "When do I get paid?": "Quand serai-je payé?",
  "Payouts are released after successful delivery confirmation and expiration of any dispute window.": "Les versements sont effectués après la confirmation de la livraison et l’expiration de la période de contestation.",
  "What happens if a buyer disputes?": "Que se passe-t-il si un acheteur ouvre un différend?",
  "Next: Access Tokens →": "Suivant : jetons d’accès →",

  "What are access tokens?": "Que sont les jetons d’accès?",
  "Buyers need access tokens to purchase tickets to sold out events. Access tokens are earned by selling tickets to sold out events on the platform.": "Les acheteurs ont besoin de jetons d’accès pour acheter des billets pour des événements à guichets fermés. Ils les gagnent en vendant sur la plateforme des billets pour de tels événements.",
  "How do access tokens work?": "Comment fonctionnent les jetons d’accès?",
  "Earning:": "Pour en gagner :",
  "One access token is earned with each ticket sold to a sold out event.": "Chaque billet vendu pour un événement à guichets fermés rapporte un jeton d’accès.",
  "Using:": "Pour les utiliser :",
  "One access token is used with each ticket purchased to a sold out event.": "Chaque billet acheté pour un événement à guichets fermés utilise un jeton d’accès.",
  "Your access tokens are tracked on this site and you can always see your access token balance and transaction history on your account page.": "Vos jetons d’accès sont comptabilisés sur ce site. Vous pouvez consulter en tout temps votre solde et votre historique de transactions dans votre compte.",
  "Do access tokens expire?": "Les jetons d’accès expirent-ils?",
  "No. They never expire. You can use them at the time of your choosing.": "Non. Ils n’expirent jamais et vous pouvez les utiliser quand vous le souhaitez.",
  "Can I use access tokens for any sold out event?": "Puis-je utiliser mes jetons d’accès pour n’importe quel événement à guichets fermés?",
  "Yes. It does not matter how you earned your access tokens. They can be used to access purchasing of any event that is sold out.": "Oui. Peu importe comment vous les avez gagnés, ils peuvent servir à acheter des billets pour n’importe quel événement à guichets fermés.",
  "Do I earn access tokens for selling tickets to events that aren't sold out?": "Est-ce que je gagne des jetons d’accès en vendant des billets pour un événement qui n’est pas à guichets fermés?",
  "No. The idea behind TrueFanTix is to build a community for actual fans to get fair access to events. We incentivize sellers to sell their tickets to sold out events within this community by rewarding them with access tokens.": "Non. TrueFanTix veut bâtir une communauté où les vrais amateurs ont un accès équitable aux événements. Nous encourageons les vendeurs à y offrir leurs billets pour les événements à guichets fermés en leur accordant des jetons d’accès.",
  "Next: Payments →": "Suivant : paiements →",

  "How does TrueFanTix process payments?": "Comment TrueFanTix traite-t-il les paiements?",
  "How do buyers pay?": "Comment les acheteurs paient-ils?",
  "Buyers pay securely by card through Stripe's secure payment system.": "Les acheteurs paient par carte de façon sécurisée au moyen du système de paiement Stripe.",
  "How do sellers receive payouts?": "Comment les vendeurs reçoivent-ils leurs versements?",
  "Seller payouts are handled automatically through Stripe Connect once the transaction is complete and any dispute window has passed.": "Les versements aux vendeurs sont traités automatiquement par Stripe Connect lorsque la transaction est terminée et que la période de contestation est écoulée.",
  "When are funds split?": "Quand les fonds sont-ils répartis?",
  "Buyer payment is processed at checkout. The seller payout is held until ticket delivery is confirmed and any dispute window has passed.": "Le paiement de l’acheteur est traité à la caisse. Le versement au vendeur est retenu jusqu’à la confirmation de la livraison et l’expiration de la période de contestation.",
  "What does the admin fee cover?": "Que couvrent les frais administratifs?",
  "The admin fee (8.75%, with a $5.00 minimum per order) covers processing costs including payment gateway fees, payment protection, platform maintenance, and dispute resolution systems. Most of the admin fee goes toward paying for the services required to run the site securely.": "Les frais administratifs (8,75 %, minimum de 5,00 $ par commande) couvrent notamment la passerelle et la protection des paiements, l’entretien de la plateforme et le règlement des différends. Ils servent principalement à payer les services nécessaires au fonctionnement sécuritaire du site.",
  "What currencies are supported?": "Quelles devises sont acceptées?",
  "We maintain separate CAD and USD accounts. Payments are made in their original currency to ensure transparency and avoid conversion fees.": "Nous tenons des comptes distincts en dollars canadiens et américains. Les paiements sont effectués dans leur devise d’origine afin d’assurer la transparence et d’éviter les frais de conversion.",
  "Is my payment information secure?": "Mes renseignements de paiement sont-ils sécurisés?",
  "Yes. We never store your full card details on our servers. All payment information is handled securely by Stripe, which is PCI DSS compliant.": "Oui. Nous ne conservons jamais les renseignements complets de votre carte sur nos serveurs. Stripe traite toutes les données de paiement de façon sécurisée conformément à la norme PCI DSS.",
  "Next: Refunds →": "Suivant : remboursements →",

  "What is the refund policy?": "Quelle est la politique de remboursement?",
  "Refunds depend on the specific situation. We handle refunds differently based on whether the event was cancelled, postponed, or if there was a delivery issue.": "Les remboursements dépendent de la situation, notamment de l’annulation ou du report de l’événement, ou d’un problème de livraison.",
  "Event Cancellation or Postponement": "Annulation ou report d’un événement",
  "If an event is officially canceled or postponed, buyers would seek refunds from the official event provider (the primary ticket seller like Ticketmaster, etc.). TrueFanTix facilitates communication but the refund ultimately comes from the original ticket issuer.": "Si un événement est officiellement annulé ou reporté, les acheteurs doivent demander un remboursement au fournisseur officiel (le vendeur primaire, comme Ticketmaster). TrueFanTix facilite les communications, mais le remboursement provient en définitive de l’émetteur d’origine.",
  "Delivery Issues": "Problèmes de livraison",
  "If tickets fail verification or delivery:": "Si les billets échouent à la vérification ou à la livraison :",
  "A dispute can be opened by the buyer": "L’acheteur peut ouvrir un différend",
  "The case will be reviewed by our team": "Notre équipe examinera le dossier",
  "If the seller cannot provide valid tickets, a refund will be issued": "Si le vendeur ne peut fournir de billets valides, un remboursement sera effectué",
  "How do I open a dispute?": "Comment ouvrir un différend?",
  "If the seller has submitted transfer proof but the tickets were not received or the transfer details look wrong, open the purchase from your Holding page and choose": "Si le vendeur a fourni une preuve de transfert, mais que les billets n’ont pas été reçus ou que les détails semblent erronés, ouvrez l’achat dans votre page En attente et choisissez",
  "Open dispute": "Ouvrir un différend",
  ". Add a short explanation and any evidence link or transfer details so our team can review it.": ". Ajoutez une brève explication ainsi que tout lien de preuve ou détail de transfert afin que notre équipe puisse examiner le dossier.",
  "What happens during a dispute?": "Que se passe-t-il pendant un différend?",
  "1. Seller payout is paused": "1. Le versement au vendeur est suspendu",
  "— No money changes hands until the dispute is resolved.": "— Aucun argent n’est versé avant le règlement du différend.",
  "2. Evidence is reviewed": "2. Les preuves sont examinées",
  "— Both parties can submit documentation to support their case.": "— Les deux parties peuvent fournir des documents à l’appui de leur position.",
  "3. Admin resolves fairly": "3. L’administration tranche équitablement",
  "— An impartial decision is made based on the evidence provided.": "— Une décision impartiale est prise selon les preuves fournies.",
  "Full Policy": "Politique complète",
  "Dispute & Refund Policy": "Politique sur les différends et les remboursements",
  ". For detailed information about refund eligibility and procedures, please review our Terms of Service.": ". Pour connaître en détail les critères et les procédures de remboursement, consultez nos conditions d’utilisation.",
  "← Back to All FAQs": "← Retour à toutes les FAQ",

  "Found a bug or something broken? Send us details and we'll jump on it.": "Vous avez trouvé un bogue ou un élément défectueux? Envoyez-nous les détails et nous nous en occuperons.",
  "If something looks wrong, we want to know. The fastest way is to email": "Si quelque chose ne fonctionne pas correctement, dites-le-nous. Le moyen le plus rapide est d’écrire à",
  "with:": "en indiquant :",
  "What you were trying to do": "Ce que vous tentiez de faire",
  "The page URL": "L’adresse URL de la page",
  "Any screenshots (if possible)": "Toute capture d’écran, si possible",
  "The exact error text": "Le texte exact de l’erreur",
  "Back to Home": "Retour à l’accueil",

  "Your privacy matters to us": "Votre vie privée nous tient à cœur",
  "Our Commitment": "Notre engagement",
  "We collect only necessary data to provide our services. We do not sell user data. We follow applicable Canadian and U.S. privacy regulations.": "Nous recueillons uniquement les données nécessaires pour fournir nos services. Nous ne vendons pas les données des utilisateurs et respectons les lois canadiennes et américaines applicables en matière de vie privée.",
  "What We Collect": "Renseignements que nous recueillons",
  "To Process Payments:": "Pour traiter les paiements :",
  "We collect payment information, billing address, and transaction history. Payment details are handled securely by Stripe; we do not store full card numbers on our servers.": "Nous recueillons les renseignements de paiement, l’adresse de facturation et l’historique des transactions. Stripe traite les données de paiement de façon sécurisée; nous ne conservons aucun numéro de carte complet sur nos serveurs.",
  "To Verify Identities:": "Pour vérifier les identités :",
  "We may collect identification documents and contact information to verify your identity and prevent fraud.": "Nous pouvons recueillir des pièces d’identité et des coordonnées afin de vérifier votre identité et de prévenir la fraude.",
  "To Prevent Fraud:": "Pour prévenir la fraude :",
  "We collect device information, IP addresses, and usage patterns to detect and prevent fraudulent activity.": "Nous recueillons des renseignements sur les appareils, les adresses IP et les habitudes d’utilisation afin de détecter et de prévenir les activités frauduleuses.",
  "To Deliver Notifications:": "Pour envoyer des notifications :",
  "We collect email addresses and phone numbers to send transaction confirmations, updates, and important account information.": "Nous recueillons les adresses courriel et les numéros de téléphone afin d’envoyer des confirmations de transaction, des mises à jour et des renseignements importants sur le compte.",
  "Spotify Artist Import:": "Importation d’artistes Spotify :",
  "If you choose to connect Spotify, we request permission to read your followed artists and top artists so you can import artist notification favorites. We store encrypted Spotify access credentials only as needed to operate the import feature. We do not use Spotify data for advertising, resale, machine learning training, or unrelated purposes.": "Si vous connectez Spotify, nous demandons l’autorisation de lire les artistes que vous suivez et vos artistes les plus écoutés afin de les importer dans vos favoris de notification. Nous conservons les identifiants d’accès Spotify sous forme chiffrée uniquement pour assurer cette fonction. Nous n’utilisons pas les données Spotify à des fins de publicité, de revente, d’entraînement automatique ou à toute autre fin sans rapport.",
  "Business Outreach:": "Communications d’affaires :",
  "We may retain business contact information published by official organizations, the source and date used to verify it, our lawful basis for contact, outgoing communication records, and unsubscribe or do-not-contact requests. Outreach is sent through our authenticated email delivery provider; we do not read the administrator's inbox or import unrelated email.": "Nous pouvons conserver les coordonnées professionnelles publiées par des organismes officiels, la source et la date de vérification, le fondement légal du contact, les communications envoyées ainsi que les demandes de désabonnement ou de non-communication. Les messages sont envoyés par notre fournisseur de courriel authentifié; nous ne lisons pas la boîte de réception de l’administrateur et n’importons aucun courriel sans rapport.",
  "What We Don't Do": "Ce que nous ne faisons pas",
  "We do not sell user data.": "Nous ne vendons pas les données des utilisateurs.",
  "Your personal information is used solely to provide and improve our services. We do not share your data with third parties for marketing purposes.": "Vos renseignements personnels servent uniquement à fournir et à améliorer nos services. Nous ne les communiquons pas à des tiers à des fins de marketing.",
  "Data Security": "Sécurité des données",
  "We implement industry-standard security measures to protect your data:": "Nous appliquons des mesures de sécurité reconnues dans l’industrie pour protéger vos données :",
  "Encryption of sensitive data in transit and at rest": "Chiffrement des données sensibles en transit et au repos",
  "Secure password hashing (bcrypt)": "Hachage sécurisé des mots de passe (bcrypt)",
  "Regular security assessments": "Évaluations de sécurité régulières",
  "Access controls and authentication": "Contrôles d’accès et authentification",
  "PCI DSS compliant payment processing via Stripe": "Traitement des paiements conforme à la norme PCI DSS par Stripe",
  "Your Rights": "Vos droits",
  "Depending on your location, you may have the right to:": "Selon votre lieu de résidence, vous pourriez avoir le droit de :",
  "Access your personal information": "Consulter vos renseignements personnels",
  "Correct inaccurate information": "Corriger des renseignements inexacts",
  "Request deletion of your data": "Demander la suppression de vos données",
  "Opt out of marketing communications": "Refuser les communications de marketing",
  "Export your data": "Exporter vos données",
  "You can disconnect Spotify from Account > Notifications at any time. Disconnecting removes our stored Spotify connection credentials and stops future Spotify artist imports. Artist notification favorites you explicitly imported into TrueFanTix can be removed from your notification interests.": "Vous pouvez déconnecter Spotify en tout temps dans Compte > Notifications. La déconnexion supprime les identifiants Spotify que nous conservons et met fin aux importations futures. Vous pouvez retirer de vos intérêts de notification les artistes que vous avez expressément importés dans TrueFanTix.",
  "Legal Compliance": "Conformité juridique",
  "We follow applicable Canadian and U.S. privacy regulations including PIPEDA (Canada) and applicable state privacy laws in the United States. We are committed to transparency and will notify users of any significant changes to this policy.": "Nous respectons les lois canadiennes et américaines applicables en matière de vie privée, notamment la LPRPDE au Canada et les lois étatiques pertinentes aux États-Unis. Nous nous engageons à faire preuve de transparence et informerons les utilisateurs de toute modification importante à cette politique.",
  "Next: Pricing & Fee Policy →": "Suivant : politique de tarification et de frais →",

  "By using TrueFanTix, you agree to the following": "En utilisant TrueFanTix, vous acceptez les conditions suivantes",
  "Agreement to Terms": "Acceptation des conditions",
  "Last Updated:": "Dernière mise à jour :",
  "February 18, 2026": "18 février 2026",
  "By using TrueFanTix, you agree to abide by these Terms of Service. Please read them carefully.": "En utilisant TrueFanTix, vous acceptez de respecter les présentes conditions d’utilisation. Veuillez les lire attentivement.",
  "1. List Tickets Truthfully": "1. Affichez les billets honnêtement",
  "You agree to list only tickets that you legally own and have the right to sell. All listing information must be accurate, including event details, seat information, and ticket authenticity. Misrepresentation is grounds for immediate account suspension.": "Vous acceptez d’afficher uniquement des billets que vous possédez légalement et que vous avez le droit de vendre. Tous les renseignements de l’annonce doivent être exacts, y compris les détails de l’événement, les sièges et l’authenticité des billets. Toute fausse déclaration peut entraîner la suspension immédiate du compte.",
  "2. Respect Face-Value Pricing Rules": "2. Respectez les règles du prix nominal",
  "TrueFanTix enforces a strict face-value pricing policy. You agree to list tickets at or below face value (including any original fees you paid). Attempting to list above face value or circumventing this rule will result in listing removal and potential account suspension.": "TrueFanTix applique une politique stricte de prix nominal. Vous acceptez d’afficher vos billets au prix nominal ou moins, y compris les frais payés à l’origine. Toute tentative de dépasser ce prix ou de contourner cette règle entraînera le retrait de l’annonce et pourrait mener à la suspension du compte.",
  "3. No Off-Platform Transactions": "3. Aucune transaction hors plateforme",
  "You agree not to attempt to move transactions off the TrueFanTix platform. This includes exchanging contact information to arrange private sales, requesting payment outside our secure system, or any other attempt to bypass our payment protection, verification, and transfer confirmation processes. Off-platform transactions void all protections and may result in permanent account ban.": "Vous acceptez de ne pas déplacer une transaction à l’extérieur de TrueFanTix. Cela comprend l’échange de coordonnées pour organiser une vente privée, la demande d’un paiement hors de notre système sécurisé ou toute tentative de contourner nos processus de protection du paiement, de vérification et de confirmation du transfert. Une transaction hors plateforme annule toutes les protections et peut entraîner la fermeture permanente du compte.",
  "4. Follow Dispute Procedures": "4. Suivez la procédure de règlement des différends",
  "In the event of a dispute, you agree to participate in good faith in our dispute resolution process. This includes providing requested evidence in a timely manner and accepting the final determination made by TrueFanTix administrators.": "En cas de différend, vous acceptez de participer de bonne foi à notre processus de règlement, notamment en fournissant rapidement les preuves demandées et en acceptant la décision finale des administrateurs de TrueFanTix.",
  "5. Treat Everyone with Courtesy and Respect": "5. Traitez tout le monde avec courtoisie et respect",
  "You agree to treat all users—buyers, sellers, and staff—with courtesy and respect. Harassment, abusive language, threats, or discriminatory behavior will not be tolerated.": "Vous acceptez de traiter tous les utilisateurs — acheteurs, vendeurs et membres du personnel — avec courtoisie et respect. Le harcèlement, les propos injurieux, les menaces et les comportements discriminatoires ne seront pas tolérés.",
  "Violation of Terms": "Violation des conditions",
  "Violation of these terms may result in account suspension or permanent termination. We reserve the right to take appropriate action against any user who violates these terms or engages in fraudulent, abusive, or harmful behavior on the platform.": "Toute violation de ces conditions peut entraîner la suspension ou la fermeture permanente du compte. Nous nous réservons le droit de prendre les mesures appropriées contre tout utilisateur qui enfreint ces conditions ou adopte un comportement frauduleux, abusif ou nuisible sur la plateforme.",
  "Additional Policies": "Politiques supplémentaires",
  "These Terms of Service work in conjunction with our other policies:": "Les présentes conditions d’utilisation s’appliquent conjointement avec nos autres politiques :",
  "Pricing & Fee Policy": "Politique de tarification et de frais",
  "Next: Privacy Policy →": "Suivant : politique de confidentialité →",

  "Our commitment to an inclusive, accessible experience for every fan.": "Notre engagement envers une expérience inclusive et accessible pour tous les amateurs.",
  "TrueFanTix is committed to providing an accessible experience for all users. If you encounter any accessibility barriers, please contact us at": "TrueFanTix s’engage à offrir une expérience accessible à tous. Si vous rencontrez un obstacle à l’accessibilité, communiquez avec nous à",

  "Pricing and Fee Policy": "Politique de tarification et de frais",
  "Transparent pricing with no hidden charges": "Une tarification transparente, sans frais cachés",
  "Our Commitment to Transparency": "Notre engagement envers la transparence",
  "Transparency is mandatory at TrueFanTix. No hidden charges, ever.": "La transparence est essentielle chez TrueFanTix. Aucun frais caché, jamais.",
  "Sellers Receive 100% of Ticket Price": "Les vendeurs reçoivent 100 % du prix du billet",
  "When you list a ticket for $100, you receive $100. No seller fees, no hidden deductions.": "Lorsque vous affichez un billet à 100 $, vous recevez 100 $. Aucuns frais de vendeur ni retenue cachée.",
  "Buyers Pay 8.75% Admin Fee (Minimum $5)": "Les acheteurs paient des frais administratifs de 8,75 % (minimum de 5 $)",
  "The buyer pays the ticket price plus an 8.75% admin fee, with a $5.00 minimum per order. This covers payment processing, payment protection, platform maintenance, and dispute resolution.": "L’acheteur paie le prix du billet plus des frais administratifs de 8,75 %, avec un minimum de 5,00 $ par commande. Ces frais couvrent le traitement et la protection des paiements, l’entretien de la plateforme et le règlement des différends.",
  "No Tax Collected at This Time": "Aucune taxe perçue pour le moment",
  "TrueFanTix is not currently collecting GST/HST or sales tax on the admin fee. This policy will be reviewed if registration or collection obligations change.": "TrueFanTix ne perçoit actuellement ni TPS/TVH ni taxe de vente sur les frais administratifs. Cette politique sera révisée si les obligations d’inscription ou de perception changent.",
  "Example Transaction": "Exemple de transaction",
  "Ticket Price": "Prix du billet",
  "Admin Fee (8.75%)": "Frais administratifs (8,75 %)",
  "Buyer Pays": "Montant payé par l’acheteur",
  "Seller Receives": "Montant reçu par le vendeur",
  "Note: TrueFanTix is not currently collecting tax on the admin fee.": "Remarque : TrueFanTix ne perçoit actuellement aucune taxe sur les frais administratifs.",
  "What the Admin Fee Covers": "Ce que couvrent les frais administratifs",
  "🔒 Payment Protection": "🔒 Protection des paiements",
  "Payout holds, transfer tracking, and delivery confirmation": "Retenue des versements, suivi des transferts et confirmation de la livraison",
  "💳 Payment Processing": "💳 Traitement des paiements",
  "Stripe Connect fees and transaction costs": "Frais Stripe Connect et coûts de transaction",
  "⚖️ Dispute Resolution": "⚖️ Règlement des différends",
  "Human oversight for conflict resolution": "Supervision humaine pour régler les conflits",
  "🛠️ Platform Maintenance": "🛠️ Entretien de la plateforme",
  "Server costs, security, and development": "Coûts des serveurs, sécurité et développement",
  "How We Compare": "Comparaison",
  "Platform": "Plateforme",
  "Seller Fee": "Frais de vendeur",
  "Buyer Fee": "Frais d’acheteur",
  "Face Value Rule": "Règle du prix nominal",
  "8.75% (minimum $5)": "8,75 % (minimum de 5 $)",
  "✓ Enforced": "✓ Appliquée",
  "Typical Secondary Market": "Marché secondaire typique",
  "✗ No limit": "✗ Aucune limite",
  "Next: Community Guidelines →": "Suivant : règles de la communauté →",

  "Help us build a positive community for fans": "Aidez-nous à bâtir une communauté positive pour les amateurs",
  "The TrueFanTix Forum": "Le forum TrueFanTix",
  "The TrueFanTix forum is open to all registered users. It's a place for fans to connect, discuss events, share reviews, and talk about their entertainment interests.": "Le forum TrueFanTix est ouvert à tous les utilisateurs inscrits. Les amateurs peuvent s’y rencontrer, discuter d’événements, partager des évaluations et parler de leurs intérêts en matière de divertissement.",
  "✅ Allowed Content": "✅ Contenu permis",
  "Event Discussion": "Discussion sur les événements",
  "Talk about upcoming concerts, shows, games, and other live events. Share excitement, ask questions, and connect with fellow fans.": "Parlez des concerts, spectacles, matchs et autres événements à venir. Partagez votre enthousiasme, posez des questions et échangez avec d’autres amateurs.",
  "Share your experiences with sellers, venues, and events. Honest reviews help build trust in our community.": "Partagez vos expériences avec les vendeurs, les salles et les événements. Des évaluations honnêtes renforcent la confiance dans notre communauté.",
  "Entertainment Interests": "Intérêts en matière de divertissement",
  "Discuss your favorite artists, teams, bands, and genres. Find people with similar interests.": "Discutez de vos artistes, équipes, groupes et genres préférés. Rencontrez des personnes qui partagent vos intérêts.",
  "❌ Not Allowed": "❌ Contenu interdit",
  "Politics": "Politique",
  "Political discussions are not permitted. This is a space for fans to connect over shared entertainment interests. There are plenty of other Social Media Communities to discuss these issues.": "Les discussions politiques ne sont pas permises. Cet espace permet aux amateurs de se réunir autour d’intérêts communs en matière de divertissement. D’autres communautés sur les médias sociaux conviennent mieux à ces sujets.",
  "Religion": "Religion",
  "Religious discussions are not allowed. Please keep conversations focused on events and entertainment. All people are welcomed here, no matter your beliefs.": "Les discussions religieuses ne sont pas permises. Veuillez vous en tenir aux événements et au divertissement. Tout le monde est bienvenu ici, quelles que soient ses croyances.",
  "Race-Based Discussion": "Discussions fondées sur la race",
  "Discussions based on race, ethnicity, or national origin are not permitted. All people are welcomed here.": "Les discussions fondées sur la race, l’origine ethnique ou l’origine nationale ne sont pas permises. Tout le monde est bienvenu ici.",
  "Harassment or Abuse": "Harcèlement ou violence verbale",
  "Any form of harassment, bullying, abusive language, or personal attacks will not be tolerated.": "Aucune forme de harcèlement, d’intimidation, de langage injurieux ou d’attaque personnelle ne sera tolérée.",
  "Off-Platform Transaction Attempts": "Tentatives de transaction hors plateforme",
  "Attempting to conduct ticket transactions outside of TrueFanTix is strictly prohibited and may result in account suspension or termination.": "Il est strictement interdit d’effectuer une transaction de billets à l’extérieur de TrueFanTix. Une telle tentative peut entraîner la suspension ou la fermeture du compte.",
  "Moderation": "Modération",
  "Moderation may remove content that violates these guidelines. Repeated violations may result in temporary or permanent suspension of forum privileges or account termination.": "La modération peut retirer tout contenu qui enfreint ces règles. Des infractions répétées peuvent entraîner la suspension temporaire ou permanente des privilèges du forum, ou la fermeture du compte.",
  "If you see content that violates these guidelines, please report it to our support team.": "Si vous voyez du contenu qui enfreint ces règles, veuillez le signaler à notre équipe de soutien.",
  "Be Kind, Be a Fan": "Soyez aimable, soyez un amateur",
  "We're all here because we love live events. Let's keep this community welcoming, positive, and focused on the shared experiences that bring us together.": "Nous sommes tous ici parce que nous aimons les événements en personne. Gardons cette communauté accueillante, positive et centrée sur les expériences communes qui nous rassemblent.",
  "Next: Our Story →": "Suivant : notre histoire →",
};

// Customer workflow pages linked from Account, Tickets, authentication, and search.
Object.assign(frenchText, {
  "Edit Profile": "Modifier le profil",
  "Profile Details": "Détails du profil",
  "How you appear to other users": "Votre nom visible par les autres utilisateurs",
  "Apt, suite, unit, etc.": "Appartement, bureau, unité, etc.",
  "Province/State *": "Province/État *",
  "Postal/ZIP code *": "Code postal/ZIP *",
  "Save Changes": "Enregistrer les modifications",
  "Saving...": "Enregistrement...",
  "Profile updated successfully!": "Profil mis à jour avec succès!",
  "Verify your account": "Vérifiez votre compte",
  "Email and phone verification are required before using verified-only features.": "La vérification du courriel et du téléphone est requise avant d’utiliser les fonctions réservées aux comptes vérifiés.",
  "Send email code": "Envoyer le code par courriel",
  "Send text code": "Envoyer le code par texto",
  "6-digit code": "Code à 6 chiffres",
  "Verified ✅": "Vérifié ✅",
  "Not verified": "Non vérifié",
  "Email verified ✅": "Courriel vérifié ✅",
  "Phone verified ✅": "Téléphone vérifié ✅",
  "When both are verified, you'll be redirected automatically.": "Lorsque les deux seront vérifiés, vous serez redirigé automatiquement.",
  "You must be logged in to verify.": "Vous devez être connecté pour effectuer la vérification.",
  "Go to login": "Aller à la connexion",
  "Change Password": "Modifier le mot de passe",
  "Current password": "Mot de passe actuel",
  "New password": "Nouveau mot de passe",
  "Confirm new password": "Confirmer le nouveau mot de passe",
  "Changing...": "Modification...",
  "Password changed successfully!": "Mot de passe modifié avec succès!",
  "New passwords do not match.": "Les nouveaux mots de passe ne correspondent pas.",
  "Notification interests": "Intérêts de notification",
  "Event distance radius": "Rayon de distance des événements",
  "No distance limit saved": "Aucune limite de distance enregistrée",
  "No limit": "Aucune limite",
  "from home": "du domicile",
  "Save radius": "Enregistrer le rayon",
  "Notification radius cleared.": "Rayon de notification effacé.",
  "Notification preference saved.": "Préférence de notification enregistrée.",
  "Notification preference removed.": "Préférence de notification supprimée.",
  "Artist": "Artiste",
  "Artists": "Artistes",
  "Team": "Équipe",
  "Teams": "Équipes",
  "Venue": "Salle",
  "Venues": "Salles",
  "Cities": "Villes",
  "Sport": "Sport",
  "Sports": "Sports",
  "Add notification": "Ajouter une notification",
  "No notification interests yet.": "Aucun intérêt de notification pour le moment.",
  "Loading preferences...": "Chargement des préférences...",
  "Import artists from Spotify": "Importer des artistes depuis Spotify",
  "Connect Spotify to import followed/top artists into notification favorites.": "Connectez Spotify pour importer les artistes suivis ou les plus écoutés dans vos favoris de notification.",
  "Find my Spotify artists": "Trouver mes artistes Spotify",
  "Select all": "Tout sélectionner",
  "Deselect all": "Tout désélectionner",
  "Hide": "Masquer",
  "Show": "Afficher",
  "Disconnect Spotify": "Déconnecter Spotify",
  "No verified catalog match found. Check the spelling or try another term.": "Aucune correspondance vérifiée trouvée dans le catalogue. Vérifiez l’orthographe ou essayez un autre terme.",
  "Sending request...": "Envoi de la demande...",
  "Request sent. TrueFanTix will research it and add it to your notifications when it is verified.": "Demande envoyée. TrueFanTix fera les recherches nécessaires et l’ajoutera à vos notifications après vérification.",
  "Purchases": "Achats",
  "Sales": "Ventes",
  "Payouts": "Versements",
  "Refunds": "Remboursements",
  "All": "Tous",
  "Pending": "En attente",
  "Instant retry needed": "Nouvelle tentative instantanée requise",
  "Waiting for your review": "En attente de votre évaluation",
  "Completed purchases that still need your seller review.": "Achats terminés pour lesquels vous devez encore évaluer le vendeur.",
  "Reviews you’ve received": "Évaluations reçues",
  "Feedback buyers have left for you as a seller.": "Commentaires laissés par les acheteurs à votre sujet comme vendeur.",
  "Reviews you’ve left": "Évaluations laissées",
  "Your review history for completed purchases.": "Historique de vos évaluations pour les achats terminés.",
  "Review needed": "Évaluation requise",
  "No buyer reviews received yet.": "Aucune évaluation d’acheteur reçue pour le moment.",
  "You’re all caught up—there are no sellers waiting for your review.": "Tout est à jour — aucun vendeur n’attend votre évaluation.",
  "Tickets — Holding": "Billets — détenus",
  "Awaiting seller transfer": "En attente du transfert du vendeur",
  "Transfer confirmed": "Transfert confirmé",
  "Transferred - awaiting final completion": "Transférés — en attente de finalisation",
  "Confirm receipt": "Confirmer la réception",
  "Open a dispute": "Ouvrir un différend",
  "Dispute opened": "Différend ouvert",
  "Submit dispute": "Soumettre le différend",
  "Opening...": "Ouverture...",
  "Working...": "Traitement...",
  "Describe what went wrong with the ticket transfer": "Décrivez le problème survenu lors du transfert des billets",
  "The seller has submitted transfer proof. Confirm receipt after the tickets are in your account, or open a dispute before the confirmation window ends.": "Le vendeur a soumis une preuve de transfert. Confirmez la réception lorsque les billets sont dans votre compte ou ouvrez un différend avant la fin du délai de confirmation.",
  "Your payment is held by TrueFanTix while the seller transfers the tickets. Seller payout is not released until you confirm receipt, the 24-hour confirmation window ends without a dispute, or an admin resolves the case.": "Votre paiement est retenu par TrueFanTix pendant le transfert des billets. Le versement au vendeur n’est libéré qu’après votre confirmation, à la fin du délai de 24 heures sans différend ou après la résolution du dossier par un administrateur.",
  "Tickets — Selling": "Billets — en vente",
  "List a ticket": "Mettre un billet en vente",
  "My active listings": "Mes annonces actives",
  "Seller status": "État du vendeur",
  "Seller verification required": "Vérification du vendeur requise",
  "You must be fully verified (email + phone + Stripe) to list tickets.": "Vous devez être entièrement vérifié (courriel, téléphone et Stripe) pour mettre des billets en vente.",
  "Choose the ticket category before listing tickets.": "Choisissez la catégorie du billet avant de le mettre en vente.",
  "Event": "Événement",
  "Event name": "Nom de l’événement",
  "Event type": "Type d’événement",
  "Date is required.": "La date est obligatoire.",
  "Venue is required.": "La salle est obligatoire.",
  "Face value must be a number greater than 0.": "Le prix nominal doit être un nombre supérieur à 0.",
  "List price must be a number greater than 0.": "Le prix de vente doit être un nombre supérieur à 0.",
  "Ticket quantity must be a whole number from 1 to 20.": "La quantité de billets doit être un nombre entier de 1 à 20.",
  "Upload the original purchase receipt before listing tickets.": "Téléversez le reçu d’achat original avant de mettre les billets en vente.",
  "General Admission": "Admission générale",
  "Sold out / offsale": "À guichets fermés / vente terminée",
  "Not sold out": "Pas à guichets fermés",
  "Listing...": "Mise en vente...",
  "Tickets successfully listed.": "Billets mis en vente avec succès.",
  "Save changes": "Enregistrer les modifications",
  "Ticket updated.": "Billet mis à jour.",
  "Ticket withdrawn.": "Billet retiré.",
  "Withdraw": "Retirer",
  "Request support review": "Demander une vérification au soutien",
  "Tickets — Seller Holding": "Billets — détenus par le vendeur",
  "Awaiting buyer confirmation": "En attente de la confirmation de l’acheteur",
  "Buyer confirmed": "Confirmation de l’acheteur reçue",
  "Auto-confirmed after 24 hours": "Confirmation automatique après 24 heures",
  "Dispute opened — payout paused": "Différend ouvert — versement suspendu",
  "Human review requested": "Vérification humaine demandée",
  "I transferred the tickets - check and submit proof": "J’ai transféré les billets — vérifier et soumettre la preuve",
  "Email Confirmation": "Confirmation par courriel",
  "Screenshot": "Capture d’écran",
  "Request Human Review": "Demander une vérification humaine",
  "Requesting human review...": "Demande de vérification humaine...",
  "Checking proof...": "Vérification de la preuve...",
  "Transfer confirmed by seller. Buyer confirmation is now pending.": "Transfert confirmé par le vendeur. La confirmation de l’acheteur est maintenant attendue.",
  "Tickets — Bought": "Billets — achetés",
  "Seller rating": "Évaluation du vendeur",
  "How was communication, ticket accuracy, and delivery?": "Comment évaluez-vous la communication, l’exactitude des billets et la livraison?",
  "Add a comment about your experience with the seller.": "Ajoutez un commentaire sur votre expérience avec le vendeur.",
  "Submit seller review": "Soumettre l’évaluation du vendeur",
  "Submitting…": "Envoi…",
  "Tickets — Sold": "Billets — vendus",
  "Search Tickets": "Rechercher des billets",
  "Search for tickets": "Rechercher des billets",
  "Artist, team, venue...": "Artiste, équipe, salle...",
  "Sort By": "Trier par",
  "Relevance": "Pertinence",
  "Newest First": "Plus récents d’abord",
  "Price: Low to High": "Prix : croissant",
  "Price: High to Low": "Prix : décroissant",
  "Min Price": "Prix minimum",
  "Max Price": "Prix maximum",
  "Load More": "Afficher plus",
  "Try a different search term or adjust filters.": "Essayez un autre terme de recherche ou modifiez les filtres.",
  "Event Details": "Détails de l’événement",
  "Pricing": "Tarification",
  "Seller Information": "Renseignements sur le vendeur",
  "Unknown Seller": "Vendeur inconnu",
  "Original Fair Value:": "Valeur équitable originale :",
  "Seller Face Value Paid:": "Prix nominal payé par le vendeur :",
  "Seller Fees Paid:": "Frais payés par le vendeur :",
  "Seller Total Paid:": "Total payé par le vendeur :",
  "Max Allowed List Price:": "Prix de vente maximal permis :",
  "You Save:": "Vous économisez :",
  "View all tickets for this event": "Voir tous les billets pour cet événement",
  "Box office sold out • Resale tickets available": "Guichet à guichets fermés • Billets de revente disponibles",
  "Create new password": "Créer un nouveau mot de passe",
  "Enter a new password for your account.": "Entrez un nouveau mot de passe pour votre compte.",
  "At least 10 characters with one letter and one number.": "Au moins 10 caractères, dont une lettre et un chiffre.",
  "Resetting...": "Réinitialisation...",
  "Your password has been reset.": "Votre mot de passe a été réinitialisé.",
  "Back to login": "Retour à la connexion",
  "Creating account...": "Création du compte...",
  "After registering, you’ll verify your email and phone.": "Après l’inscription, vous vérifierez votre courriel et votre téléphone.",
  "Show passwords": "Afficher les mots de passe",
  "Hide passwords": "Masquer les mots de passe",
  "Logging in...": "Connexion...",
  "Please enter your email or phone number.": "Veuillez entrer votre courriel ou votre numéro de téléphone.",
  "Please enter your password.": "Veuillez entrer votre mot de passe.",
  "Login failed. Please check your credentials and try again.": "Échec de la connexion. Vérifiez vos renseignements et réessayez.",
  "email@example.com or 4165551234": "courriel@exemple.ca ou 4165551234",
  "If your account isn’t verified yet, you’ll be sent to verification after login.": "Si votre compte n’est pas encore vérifié, vous serez dirigé vers la vérification après la connexion.",
  "New here?": "Nouveau ici?",
  "Network error. Please try again.": "Erreur réseau. Veuillez réessayer.",
  "Forgot password?": "Mot de passe oublié?",
  "Send reset link": "Envoyer le lien de réinitialisation",
  "Sending...": "Envoi...",
  "Please enter your email address.": "Veuillez entrer votre adresse courriel.",
  "Please enter a valid email address.": "Veuillez entrer une adresse courriel valide.",
  "If an account exists with this email, you will receive password reset instructions.": "Si un compte correspond à ce courriel, vous recevrez les instructions de réinitialisation du mot de passe.",
  "Order summary": "Sommaire de la commande",
  "Tax": "Taxe",
  "Failed to initialize payment.": "Impossible d’initialiser le paiement.",
  "Failed to load order.": "Impossible de charger la commande.",
  "Checkout was not completed": "Le paiement n’a pas été terminé",
  "Payment still needs attention": "Le paiement nécessite encore votre attention",
  "This order cannot be treated as bought because payment did not complete successfully.": "Cette commande ne peut pas être considérée comme achetée, car le paiement n’a pas été effectué correctement.",
  "Create Discussion": "Créer une discussion",
  "Creating...": "Création...",
  "What's your discussion about?": "Quel est le sujet de votre discussion?",
  "Share your thoughts, questions, or insights...": "Partagez vos réflexions, vos questions ou vos idées...",
  "Please log in before creating a discussion.": "Veuillez vous connecter avant de créer une discussion.",
  "Please verify your email and phone number before creating a discussion.": "Veuillez vérifier votre courriel et votre numéro de téléphone avant de créer une discussion.",
  "Ticket unavailable": "Billet non disponible",
  "Venue location unavailable": "Emplacement de la salle non disponible",
  "Address": "Adresse",
  "Changing your phone will require re-verification.": "La modification de votre téléphone exigera une nouvelle vérification.",
  "Display name": "Nom affiché",
  "← Back to Account": "← Retour au compte",
  "Redirecting…": "Redirection…",
  "Passwords do not match.": "Les mots de passe ne correspondent pas.",
  "Add": "Ajouter",
  "Remove": "Supprimer",
  "Add artists, teams, venues, cities, and sports for alerts and sold-out access matching.": "Ajoutez des artistes, équipes, salles, villes et sports pour recevoir des alertes et repérer les événements à guichets fermés.",
  "Connect Spotify": "Connecter Spotify",
  "Connect Spotify first to find artists for import.": "Connectez d’abord Spotify pour trouver des artistes à importer.",
  "Current radius:": "Rayon actuel :",
  "Import selected": "Importer la sélection",
  "No catalog match yet; will request admin review if selected": "Aucune correspondance dans le catalogue; une vérification administrative sera demandée si sélectionné",
  "Spotify connected. Open to find and import artists.": "Spotify est connecté. Ouvrez la section pour trouver et importer des artistes.",
  "Access Tokens Δ": "Jetons d’accès Δ",
  "Access token transaction history": "Historique des transactions de jetons d’accès",
  "Amount": "Montant",
  "Balance After": "Solde après",
  "Bank delivery": "Dépôt bancaire",
  "Coming next — this tab will be populated soon.": "À venir — cet onglet sera bientôt alimenté.",
  "Current access token balance": "Solde actuel de jetons d’accès",
  "Event Date": "Date de l’événement",
  "Fee": "Frais",
  "Kind": "Type",
  "Loading transaction history…": "Chargement de l’historique des transactions…",
  "Net": "Net",
  "No access token transactions yet.": "Aucune transaction de jetons d’accès pour le moment.",
  "No payouts yet.": "Aucun versement pour le moment.",
  "No purchases yet.": "Aucun achat pour le moment.",
  "No refunds yet.": "Aucun remboursement pour le moment.",
  "No sales yet.": "Aucune vente pour le moment.",
  "Order": "Commande",
  "Order Status": "État de la commande",
  "Payout history": "Historique des versements",
  "Provider": "Fournisseur",
  "Purchase history": "Historique des achats",
  "Reference": "Référence",
  "Refund history": "Historique des remboursements",
  "Sales history": "Historique des ventes",
  "Source": "Source",
  "Status": "État",
  "Ticket": "Billet",
  "When": "Date",
  "Loading reviews…": "Chargement des évaluations…",
  "You haven’t left any seller reviews yet.": "Vous n’avez encore laissé aucune évaluation de vendeur.",
  "No holding tickets": "Aucun billet détenu",
  "Loading holding tickets...": "Chargement des billets détenus...",
  "Payment protected until delivery": "Paiement protégé jusqu’à la livraison",
  "Purchase complete": "Achat terminé",
  "Purchased": "Acheté",
  "Confirmation deadline": "Échéance de confirmation",
  "Missing or incorrect ticket? Open dispute": "Billet manquant ou incorrect? Ouvrir un différend",
  "Is this dispute about all tickets in this order?": "Ce différend concerne-t-il tous les billets de cette commande?",
  "Yes — all tickets": "Oui — tous les billets",
  "No — specific tickets": "Non — certains billets",
  "Upload supporting documents (optional)": "Téléverser des documents justificatifs (facultatif)",
  "Attached:": "Pièces jointes :",
  "All tickets in this order are selected.": "Tous les billets de cette commande sont sélectionnés.",
  "Opening a dispute pauses seller payout for the entire order while the issue is reviewed.": "L’ouverture d’un différend suspend le versement au vendeur pour toute la commande pendant l’examen du problème.",
  "No active listings yet.": "Aucune annonce active pour le moment.",
  "Loading your active listings…": "Chargement de vos annonces actives…",
  "Active listings will appear here once seller verification is complete.": "Les annonces actives apparaîtront ici lorsque la vérification du vendeur sera terminée.",
  "Seller approved": "Vendeur autorisé",
  "Selling is locked until seller verification is complete.": "La vente est verrouillée jusqu’à la fin de la vérification du vendeur.",
  "Go to verification": "Aller à la vérification",
  "Ticket category": "Catégorie du billet",
  "Select a category...": "Sélectionner une catégorie...",
  "Artist, team, or sport": "Artiste, équipe ou sport",
  "Start typing an artist, team, or sport...": "Commencez à saisir un artiste, une équipe ou un sport...",
  "Start typing a venue...": "Commencez à saisir une salle...",
  "No verified artist, team, sport, or show match found.": "Aucune correspondance vérifiée trouvée pour l’artiste, l’équipe, le sport ou le spectacle.",
  "No verified venue match found.": "Aucune salle vérifiée correspondante trouvée.",
  "Event date": "Date de l’événement",
  "Date and time": "Date et heure",
  "Hour": "Heure",
  "Minutes": "Minutes",
  "AM/PM": "AM/PM",
  "Currency": "Devise",
  "CAD - Canadian dollars": "CAD — dollars canadiens",
  "USD - US dollars": "USD — dollars américains",
  "How many tickets?": "Combien de billets?",
  "Seating information": "Renseignements sur les places",
  "Section": "Section",
  "Row": "Rangée",
  "Seat": "Siège",
  "General Admission tickets": "Billets d’admission générale",
  "Face value per ticket": "Prix nominal par billet",
  "Eligible fees paid per ticket": "Frais admissibles payés par billet",
  "List price per ticket": "Prix de vente par billet",
  "Maximum list price:": "Prix de vente maximal :",
  "Purchase receipt proof": "Preuve du reçu d’achat",
  "Upload the purchase receipt and confirm the receipt values before listing.": "Téléversez le reçu d’achat et confirmez ses valeurs avant la mise en vente.",
  "Uploaded:": "Téléversé :",
  "Think the automated review is wrong?": "Vous croyez que la vérification automatisée est erronée?",
  "Refresh listings": "Actualiser les annonces",
  "No seller holding orders": "Aucune commande détenue par le vendeur",
  "Loading seller holding...": "Chargement des billets détenus par le vendeur...",
  "Seller Holding": "Billets détenus par le vendeur",
  "Sold tickets awaiting transfer or buyer confirmation will appear here.": "Les billets vendus en attente de transfert ou de confirmation de l’acheteur apparaîtront ici.",
  "Transfer the tickets outside TrueFanTix first": "Transférez d’abord les billets à l’extérieur de TrueFanTix",
  "Open the original ticket platform, such as Ticketmaster or AXS.": "Ouvrez la plateforme de billets d’origine, comme Ticketmaster ou AXS.",
  "Transfer all tickets in this order to": "Transférez tous les billets de cette commande à",
  "the buyer email shown above": "l’adresse courriel de l’acheteur indiquée ci-dessus",
  "Transfer by": "Transférer avant le",
  "Buyer confirm by": "Confirmation de l’acheteur avant le",
  "Buyer:": "Acheteur :",
  "Proof type": "Type de preuve",
  "Proof note": "Note sur la preuve",
  "Upload transfer proof": "Téléverser la preuve de transfert",
  "Ready to check:": "Prêt pour la vérification :",
  "Back to Account": "Retour au compte",
  "No tickets yet": "Aucun billet pour le moment",
  "Loading your tickets...": "Chargement de vos billets...",
  "Completed purchases will appear here. Pending transfers are shown in Holding. Browse available tickets on the": "Les achats terminés apparaîtront ici. Les transferts en attente sont affichés dans Billets détenus. Parcourez les billets disponibles sur la",
  "homepage": "page d’accueil",
  "Review seller": "Évaluer le vendeur",
  "Comments": "Commentaires",
  "Share an honest positive or negative experience. Your rating will appear on the seller’s profile.": "Partagez honnêtement votre expérience, positive ou négative. Votre évaluation apparaîtra sur le profil du vendeur.",
  "Coming next": "À venir",
  "We’ll show your completed sales, payout status, and transaction records.": "Nous afficherons vos ventes terminées, l’état des versements et les relevés de transactions.",
});

export function translateText(text: string, language: SiteLanguage): string {
  if (language === "en") return text;
  const exact = frenchText[text];
  if (exact) return exact;

  const replacements: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [/^Back to (.+)$/, (match) => `Retour à ${frenchText[match[1]] ?? match[1]}`],
    [/^Signed in as (.+)$/, (match) => `Connecté en tant que ${match[1]}`],
    [/^(.+) item waiting for you$/, (match) => `${match[1]} élément en attente`],
    [/^(.+) items waiting for you$/, (match) => `${match[1]} éléments en attente`],
    [/^Updated (.+)$/, (match) => `Mis à jour ${match[1]}`],
    [/^(\d+) reply$/, (match) => `${match[1]} réponse`],
    [/^(\d+) replies$/, (match) => `${match[1]} réponses`],
    [/^(\d+) post$/, (match) => `${match[1]} publication`],
    [/^(\d+) posts$/, (match) => `${match[1]} publications`],
    [/^by (.+)$/, (match) => `par ${match[1]}`],
    [/^From (.+)$/, (match) => `De la part de ${match[1]}`],
    [/^For (.+)$/, (match) => `Pour ${match[1]}`],
    [/^(\d+) event$/, (match) => `${match[1]} événement`],
    [/^(\d+) events$/, (match) => `${match[1]} événements`],
    [/^(\d+) ticket available$/, (match) => `${match[1]} billet disponible`],
    [/^(\d+) tickets available$/, (match) => `${match[1]} billets disponibles`],
    [/^(\d+) event(?:s)? • (\d+) ticket(?:s)? available$/, (match) => `${match[1]} événement${match[1] === "1" ? "" : "s"} • ${match[2]} billet${match[2] === "1" ? " disponible" : "s disponibles"}`],
    [/^(\d+) selected · (.+) subtotal$/, (match) => `${match[1]} sélectionné${match[1] === "1" ? "" : "s"} · sous-total de ${match[2]}`],
    [/^Selected (.+): (.+)$/, (match) => `${match[1]} sélectionné : ${match[2]}`],
    [/^Uses your home address in (.+) to limit event notifications to places you are willing to travel\.$/, (match) => `Utilise votre adresse domiciliaire à ${match[1]} pour limiter les notifications aux événements situés dans les endroits où vous êtes prêt à vous déplacer.`],
    [/^Start typing an? (artist|team|venue|city|sport)\.\.\.$/, (match) => {
      const labels: Record<string, string> = {
        artist: "un artiste",
        team: "une équipe",
        venue: "une salle",
        city: "une ville",
        sport: "un sport",
      };
      return `Commencez à saisir ${labels[match[1]]}...`;
    }],
    [/^Request this (artist|team|venue|city|sport)$/, (match) => {
      const labels: Record<string, string> = {
        artist: "l’ajout de cet artiste",
        team: "l’ajout de cette équipe",
        venue: "l’ajout de cette salle",
        city: "l’ajout de cette ville",
        sport: "l’ajout de ce sport",
      };
      return `Demander ${labels[match[1]]}`;
    }],
  ];
  for (const [pattern, replacement] of replacements) {
    const match = text.match(pattern);
    if (match) return replacement(match);
  }
  return text;
}
