export type SiteLanguage = "en" | "fr";

export const LANGUAGE_STORAGE_KEY = "truefantix-language";
export const LANGUAGE_COOKIE = "tft_language";

export const frenchText: Record<string, string> = {
  "Home": "Accueil",
  "Tickets": "Billets",
  "Forum": "Forum",
  "Account": "Compte",
  "Profile": "Profil",
  "Change password": "Modifier le mot de passe",
  "Notifications": "Notifications",
  "Transaction history": "Historique des transactions",
  "My tickets": "Mes billets",
  "Verify": "Vérifier",
  "Login": "Connexion",
  "Log in": "Se connecter",
  "Log out": "Se déconnecter",
  "Logging out...": "Déconnexion...",
  "Create account": "Créer un compte",
  "Back": "Retour",
  "Checking session…": "Vérification de la session…",
  "Not signed in": "Non connecté",
  "Signed in as": "Connecté en tant que",
  "not verified": "non vérifié",
  "Action required": "Action requise",
  "Resolve now →": "Régler maintenant →",
  "Search": "Rechercher",
  "Search tickets": "Rechercher des billets",
  "Buy tickets": "Acheter des billets",
  "Sell tickets": "Vendre des billets",
  "Buy Tickets": "Acheter des billets",
  "Sell Tickets": "Vendre des billets",
  "Learn more": "En savoir plus",
  "View details": "Voir les détails",
  "Continue": "Continuer",
  "Cancel": "Annuler",
  "Save": "Enregistrer",
  "Submit": "Soumettre",
  "Confirm": "Confirmer",
  "Close": "Fermer",
  "Edit": "Modifier",
  "Delete": "Supprimer",
  "Loading...": "Chargement...",
  "Loading…": "Chargement…",
  "Email": "Courriel",
  "Email address": "Adresse courriel",
  "Password": "Mot de passe",
  "First name": "Prénom",
  "Last name": "Nom de famille",
  "Phone": "Téléphone",
  "City": "Ville",
  "Province": "Province",
  "Country": "Pays",
  "Price": "Prix",
  "Quantity": "Quantité",
  "Total": "Total",
  "Continue to checkout": "Passer à la caisse",
  "Checkout": "Paiement",
  "Order summary": "Sommaire de la commande",
  "Payment": "Paiement",
  "Payment method": "Mode de paiement",
  "Back to tickets": "Retour aux billets",
  "No tickets found": "Aucun billet trouvé",
  "Try again": "Réessayer",
  "Something went wrong": "Une erreur s’est produite",
  "Required": "Obligatoire",
  "Optional": "Facultatif",
  "Previous": "Précédent",
  "Next": "Suivant",
  "About": "À propos",
  "Our Story": "Notre histoire",
  "How It Works": "Fonctionnement",
  "Why Face Value": "Pourquoi le prix nominal",
  "Trust & Safety": "Confiance et sécurité",
  "Trust and Safety": "Confiance et sécurité",
  "Buying Tickets": "Acheter des billets",
  "Selling Tickets": "Vendre des billets",
  "Access Tokens": "Jetons d’accès",
  "Payments": "Paiements",
  "Refunds": "Remboursements",
  "Contact": "Nous joindre",
  "Email Us": "Nous écrire",
  "Report an Issue": "Signaler un problème",
  "Privacy Policy": "Politique de confidentialité",
  "Terms of Service": "Conditions d’utilisation",
  "Accessibility": "Accessibilité",
  "Community Guidelines": "Règles de la communauté",
  "All rights reserved.": "Tous droits réservés.",
  "Built for fans — not scalpers.": "Conçu pour les amateurs — pas pour les revendeurs.",
  "A fan-first ticket marketplace focused on fairness, transparency, and resale at or below face value.":
    "Une plateforme de billets pensée pour les amateurs, axée sur l’équité, la transparence et la revente au prix nominal ou moins.",
  "English": "English",
  "French": "Français",
  "Language": "Langue",
  "Select language": "Choisir la langue",
  "Settings": "Paramètres",
  "Security": "Sécurité",
  "Reviews": "Évaluations",
  "Bought": "Achetés",
  "Sold": "Vendus",
  "Selling": "En vente",
  "Holding": "En attente",
  "Forgot password?": "Mot de passe oublié?",
  "Reset password": "Réinitialiser le mot de passe",
  "Sign up": "S’inscrire",
  "Already have an account?": "Vous avez déjà un compte?",
  "Don't have an account?": "Vous n’avez pas de compte?",
  "Help": "Aide",
  "Frequently Asked Questions": "Foire aux questions",
  "Browse Tickets": "Parcourir les billets",
  "Featured Tickets": "Billets en vedette",
  "List Tickets for Sale": "Mettre des billets en vente",
  "Create your free account": "Créez votre compte gratuit",
  "Community Forum": "Forum communautaire",
  "View all discussions": "Voir toutes les discussions",
  "No discussions yet": "Aucune discussion pour le moment",
  "Loading latest discussions…": "Chargement des discussions récentes…",
  "Latest discussions (showing up to 6).": "Discussions récentes (jusqu’à 6 affichées).",
  "Select featured tickets to checkout directly.": "Choisissez des billets en vedette pour passer directement à la caisse.",
  "Limited-time launch promotion": "Promotion de lancement à durée limitée",
  "Create your free account and receive 4 access tokens. Sell tickets during the promotion and earn an additional 4 access tokens for every ticket sold.":
    "Créez votre compte gratuit et recevez 4 jetons d’accès. Vendez des billets pendant la promotion et obtenez 4 jetons d’accès supplémentaires pour chaque billet vendu.",
  "Welcome to": "Bienvenue sur",
  "Buy and sell tickets at or below face value. Secure, fair, and fan-first.": "Achetez et vendez des billets au prix nominal ou moins. Sécuritaire, équitable et pensé pour les amateurs.",
  "Could not load tickets": "Impossible de charger les billets",
  "Loading tickets...": "Chargement des billets...",
  "No tickets match your search.": "Aucun billet ne correspond à votre recherche.",
  "All Event Types": "Tous les types d’événements",
  "Any Price": "Tous les prix",
  "Any Price Type": "Tous les types de prix",
  "Below Face Value": "Sous le prix nominal",
  "Face Value": "Prix nominal",
  "Start date": "Date de début",
  "End date": "Date de fin",
  "Concert": "Concert",
  "Comedy": "Humour",
  "Conference": "Conférence",
  "Festival": "Festival",
  "Theatre": "Théâtre",
  "Opera": "Opéra",
  "Other": "Autre",
  "Sports: Baseball": "Sports : baseball",
  "Sports: Basketball": "Sports : basketball",
  "Sports: Football": "Sports : football",
  "Sports: Hockey": "Sports : hockey",
  "Sports: Lacrosse": "Sports : crosse",
  "Sports: Soccer": "Sports : soccer",
  "Sports: Other": "Sports : autre",
  "Create an account": "Créer un compte",
  "Email or phone": "Courriel ou téléphone",
  "Use your email or phone number.": "Utilisez votre courriel ou votre numéro de téléphone.",
  "Confirm password": "Confirmer le mot de passe",
  "Display name (optional)": "Nom affiché (facultatif)",
  "Postal / ZIP": "Code postal / ZIP",
  "Province / State": "Province / État",
  "Street address": "Adresse",
  "Street address 2 (optional)": "Complément d’adresse (facultatif)",
  "United States": "États-Unis",
  "Overall verification": "Vérification générale",
  "Loading account...": "Chargement du compte...",
  "Fast payout": "Paiement rapide",
  "Standard payout": "Paiement standard",
  "Report issue": "Signaler un problème",
  "Send": "Envoyer",
  "Reply": "Répondre",
  "New post": "Nouvelle publication",
  "New thread": "Nouvelle discussion",
  "Post reply": "Publier la réponse",
  "Updated": "Mis à jour",
  "reply": "réponse",
  "replies": "réponses",
};

export function translateText(text: string, language: SiteLanguage): string {
  if (language === "en") return text;
  const exact = frenchText[text];
  if (exact) return exact;

  const replacements: Array<[RegExp, (match: RegExpMatchArray) => string]> = [
    [/^Back to (.+)$/, (match) => `Retour à ${frenchText[match[1]] ?? match[1]}`],
    [/^Signed in as (.+)$/, (match) => `Connecté en tant que ${match[1]}`],
    [/^(.+) item waiting for you$/, (match) => `${match[1]} élément en attente`],
    [/^(.+) items waiting for you$/, (match) => `${match[1]} éléments en attente`],
    [/^Updated (.+)$/, (match) => `Mis à jour ${match[1]}`],
    [/^(\d+) reply$/, (match) => `${match[1]} réponse`],
    [/^(\d+) replies$/, (match) => `${match[1]} réponses`],
  ];
  for (const [pattern, replacement] of replacements) {
    const match = text.match(pattern);
    if (match) return replacement(match);
  }
  return text;
}
