"use client";
import React from "react";
import Link from "next/link";

type Contact = { id:string; organization:string|null; subjectName:string|null; contactName:string|null; role:string|null; email:string|null; category:string; sourceUrl:string|null; verifiedAt:string|null; confidence:string|null; researchStatus:string|null; consentBasis:string; consentEvidence:string|null; lastContactedAt:string|null; unsubscribedAt:string|null; suppressionReason:string|null };
type Campaign = { id:string; name:string; status:string; createdAt:string; _count:{recipients:number}; statusCounts:Record<string,number> };
type Template = { id:string; name:string; subject:string; bodyText:string };
const field: React.CSSProperties = { padding:"9px 10px", borderRadius:8, border:"1px solid rgba(0,0,0,.16)", background:"white" };
const button: React.CSSProperties = { padding:"9px 12px", borderRadius:8, border:"1px solid rgba(0,0,0,.16)", background:"white", fontWeight:800, cursor:"pointer" };

async function jsonFetch(url:string, options?:RequestInit) { const res=await fetch(url,options); const data=await res.json().catch(()=>null); if(!res.ok||!data?.ok) throw new Error(data?.error||data?.message||"Request failed."); return data; }
export default function OutreachPage(){
  const [contacts,setContacts]=React.useState<Contact[]>([]),[campaigns,setCampaigns]=React.useState<Campaign[]>([]),[templates,setTemplates]=React.useState<Template[]>([]);
  const [selected,setSelected]=React.useState<Set<string>>(new Set()),[q,setQ]=React.useState(""),[category,setCategory]=React.useState(""),[categories,setCategories]=React.useState<string[]>([]),[sendable,setSendable]=React.useState(false);
  const [error,setError]=React.useState<string|null>(null),[notice,setNotice]=React.useState<string|null>(null),[loading,setLoading]=React.useState(true);
  const [delivery,setDelivery]=React.useState<{configured:boolean;sender:string}|null>(null);
  const [compose,setCompose]=React.useState({name:"",subject:"",bodyText:"Hi {{firstName}},\n\n\n\nThanks,\nMarc\nTrueFanTix"});
  const load=React.useCallback(async()=>{setLoading(true);setError(null);try{const params=new URLSearchParams({take:"100"});if(q)params.set("q",q);if(category)params.set("category",category);if(sendable)params.set("sendable","true");const [c,ca,t,d]=await Promise.all([jsonFetch(`/api/admin/outreach/contacts?${params}`),jsonFetch("/api/admin/outreach/campaigns"),jsonFetch("/api/admin/outreach/templates"),jsonFetch("/api/admin/outreach/delivery-status")]);setContacts(c.items);setCategories(c.categories);setCampaigns(ca.items);setTemplates(t.items);setDelivery(d);}catch(e:any){setError(e.message)}finally{setLoading(false)}},[q,category,sendable]);
  React.useEffect(()=>{load()},[load]);
  const toggle=(id:string)=>setSelected(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
  const updateBasis=async(contact:Contact,basis:string)=>{try{await jsonFetch("/api/admin/outreach/contacts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:contact.id,consentBasis:basis,consentEvidence:basis==="CONSPICUOUSLY_PUBLISHED"?`Address and relevant role evidenced by ${contact.sourceUrl||"official source"}`:contact.consentEvidence})});await load()}catch(e:any){setError(e.message)}};
  const createCampaign=async()=>{setError(null);setNotice(null);try{const data=await jsonFetch("/api/admin/outreach/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...compose,contactIds:[...selected]})});setNotice(`Campaign created with ${data.item._count.recipients} recipient(s)${data.skipped?`; ${data.skipped} unsafe or duplicate selection(s) skipped`:""}.`);setSelected(new Set());setCompose(x=>({...x,name:""}));await load()}catch(e:any){setError(e.message)}};
  const saveTemplate=async()=>{const name=prompt("Template name");if(!name)return;try{await jsonFetch("/api/admin/outreach/templates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,subject:compose.subject,bodyText:compose.bodyText})});setNotice("Template saved.");await load()}catch(e:any){setError(e.message)}};
  const send=async(campaign:Campaign)=>{if(!delivery?.configured){setError("Email delivery setup is not complete yet.");return}const confirmation=prompt(`This sends up to 10 individual emails from marc@truefantix.com now. Type the exact campaign name to confirm:\n\n${campaign.name}`);if(confirmation===null)return;try{const data=await jsonFetch(`/api/admin/outreach/campaigns/${campaign.id}/send`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation,limit:10})});setNotice(`Sent ${data.sent}; failed ${data.failed}; ${data.remaining} still pending.`);await load()}catch(e:any){setError(e.message)}};
  const suppress=async()=>{const email=prompt("Email address to suppress globally");if(!email)return;try{await jsonFetch("/api/admin/outreach/suppressions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,reason:"MANUAL"})});setNotice(`${email} added to the do-not-contact list.`);await load()}catch(e:any){setError(e.message)}};
  const applyTemplate=(id:string)=>{const t=templates.find(x=>x.id===id);if(t)setCompose(x=>({...x,subject:t.subject,bodyText:t.bodyText}))};
  const previewContact=contacts.find(contact=>selected.has(contact.id));
  const preview=(value:string)=>{if(!previewContact)return value;const firstName=(previewContact.contactName||"").trim().split(/\s+/)[0]||"there";const values:Record<string,string>={firstName,contactName:previewContact.contactName||"",organization:previewContact.organization||"",subjectName:previewContact.subjectName||"",role:previewContact.role||"",email:previewContact.email||""};return value.replace(/{{\s*([a-zA-Z][\w]*)\s*}}/g,(_match,key)=>values[key]||"")};
  return <main style={{maxWidth:1280,margin:"32px auto",padding:16}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h1 style={{margin:0,fontSize:30}}>Outreach & contacts</h1><div style={{marginTop:6}}><Link href="/admin">← Admin</Link> · Evidence-backed contacts, campaigns, history and suppression</div></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span style={{padding:"8px 10px",borderRadius:8,background:delivery?.configured?"#dcfce7":"#fef3c7"}}>{delivery?.configured?"Sender ready: marc@truefantix.com · replies forward to Gmail":"Email delivery setup required—sending is disabled"}</span><button style={button} onClick={suppress}>Add suppression</button></div></div>
    {error&&<div role="alert" style={{marginTop:14,padding:12,background:"#fee2e2",borderRadius:8,color:"#991b1b"}}>{error}</div>}{notice&&<div style={{marginTop:14,padding:12,background:"#dcfce7",borderRadius:8,color:"#166534"}}>{notice}</div>}
    <section style={{marginTop:18,padding:16,border:"1px solid #ddd",borderRadius:10,background:"white"}}><h2 style={{marginTop:0}}>1. Choose contacts</h2><div style={{display:"grid",gridTemplateColumns:"minmax(220px,2fr) repeat(2,minmax(150px,1fr)) auto",gap:8}}><input style={field} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search team, artist, organization, role or email"/><select style={field} value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(x=><option key={x}>{x}</option>)}</select><label style={{display:"flex",alignItems:"center",gap:7}}><input type="checkbox" checked={sendable} onChange={e=>setSendable(e.target.checked)}/>Show sendable only</label><button style={button} onClick={load}>Refresh</button></div><p style={{fontSize:13,opacity:.72}}>A contact is sendable only after its legal/contact basis is recorded, its official source is retained, and its email is not suppressed. Shared agency inboxes are shown on each represented artist but are deduplicated within a campaign.</p>
      <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr>{["Pick","Organization / subject","Contact","Email","Evidence","Contact basis","History"].map(x=><th key={x} style={{padding:8,textAlign:"left",borderBottom:"1px solid #ddd"}}>{x}</th>)}</tr></thead><tbody>{contacts.map(c=>{const blocked=!!c.suppressionReason||!!c.unsubscribedAt;return <tr key={c.id} style={{opacity:blocked?.6:1}}><td style={{padding:8,borderBottom:"1px solid #eee"}}><input type="checkbox" checked={selected.has(c.id)} onChange={()=>toggle(c.id)} disabled={!c.email||blocked}/></td><td style={{padding:8,borderBottom:"1px solid #eee"}}><strong>{c.organization||c.subjectName||"—"}</strong><br/><span style={{opacity:.7}}>{c.subjectName!==c.organization?c.subjectName:""} {c.category}</span></td><td style={{padding:8,borderBottom:"1px solid #eee"}}>{c.contactName||"Departmental contact"}<br/><span style={{opacity:.7}}>{c.role}</span></td><td style={{padding:8,borderBottom:"1px solid #eee"}}>{c.email||"No public email"}{blocked&&<><br/><strong style={{color:"#991b1b"}}>DO NOT CONTACT</strong></>}</td><td style={{padding:8,borderBottom:"1px solid #eee"}}>{c.sourceUrl?<a href={c.sourceUrl} target="_blank" rel="noreferrer">Official source</a>:"Missing"}<br/><span style={{opacity:.7}}>{c.confidence} {c.verifiedAt?new Date(c.verifiedAt).toLocaleDateString():""}</span></td><td style={{padding:8,borderBottom:"1px solid #eee"}}><select style={{...field,padding:6}} value={c.consentBasis} onChange={e=>updateBasis(c,e.target.value)}><option value="UNASSESSED">Unassessed</option><option value="CONSPICUOUSLY_PUBLISHED">Published business address</option><option value="EXPRESS_CONSENT">Express consent</option><option value="EXISTING_BUSINESS_RELATIONSHIP">Existing relationship</option><option value="NOT_REQUIRED">Not required</option></select></td><td style={{padding:8,borderBottom:"1px solid #eee"}}>{c.lastContactedAt?new Date(c.lastContactedAt).toLocaleDateString():"Never"}</td></tr>})}</tbody></table></div>{loading&&<p>Loading…</p>}</section>
    <section style={{marginTop:18,padding:16,border:"1px solid #ddd",borderRadius:10,background:"white"}}><h2 style={{marginTop:0}}>2. Prepare campaign <small style={{fontWeight:400}}>({selected.size} selected)</small></h2><div style={{display:"grid",gap:9}}><input style={field} placeholder="Campaign name" value={compose.name} onChange={e=>setCompose({...compose,name:e.target.value})}/><div style={{display:"flex",gap:8}}><select style={field} defaultValue="" onChange={e=>applyTemplate(e.target.value)}><option value="">Load a template…</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button style={button} onClick={saveTemplate}>Save current as template</button></div><input style={field} placeholder="Subject — supports {{firstName}}, {{organization}}, {{subjectName}}, {{role}}" value={compose.subject} onChange={e=>setCompose({...compose,subject:e.target.value})}/><textarea style={{...field,minHeight:180,fontFamily:"inherit"}} value={compose.bodyText} onChange={e=>setCompose({...compose,bodyText:e.target.value})}/>{previewContact&&<div style={{padding:14,border:"1px solid #bfdbfe",borderRadius:8,background:"#eff6ff"}}><strong>Personalized preview for {previewContact.email}</strong><div style={{marginTop:8}}><strong>Subject:</strong> {preview(compose.subject)||"(empty)"}</div><pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit",marginBottom:0}}>{preview(compose.bodyText)}</pre></div>}<button style={{...button,background:"#0f172a",color:"white",justifySelf:"start"}} disabled={!selected.size} onClick={createCampaign}>Create reviewed draft campaign</button></div></section>
    <section style={{marginTop:18,padding:16,border:"1px solid #ddd",borderRadius:10,background:"white"}}><h2 style={{marginTop:0}}>3. Campaign history</h2>{campaigns.length===0?<p>No campaigns yet.</p>:campaigns.map(c=><div key={c.id} style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:"1px solid #eee",alignItems:"center"}}><div><strong>{c.name}</strong> · {c.status}<br/><span style={{fontSize:13,opacity:.72}}>{c._count.recipients} recipient(s) · {Object.entries(c.statusCounts||{}).map(([k,v])=>`${k}: ${v}`).join(" · ")}</span></div>{["DRAFT","SENDING"].includes(c.status)&&<button style={{...button,background:"#064a93",color:"white"}} onClick={()=>send(c)}>Send next 10</button>}</div>)}</section>
  </main>
}
